packages/formation/package.json, packages/formation/sass/core.scss, packages/formation/sass/utilities/_measure.scss
This PR will create a measure utility. For details of how this utility works, see here:
https://department-of-veterans-affairs.github.io/vets-design-system-documentation/utilities/measure.html
=> create measure utility

packages/formation/package.json, packages/formation/sass/core.scss, packages/formation/sass/utilities/_line-height.scss
This PR will create a line-height utility. For details how that works: 
https://department-of-veterans-affairs.github.io/vets-design-system-documentation/utilities/line-height.html
=> create line height utility

Jenkinsfile, packages/documentation/README.md, packages/documentation/gatsby-config.js, packages/documentation/package.json
adds doc publication task to the jenkins pipeline
=> WIP - documentation publication

packages/formation/package.json
Bumping patch version to publish updates from https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/5.
=> Bump patch version

packages/documentation/gatsby-config.js, packages/documentation/package.json, packages/documentation/yarn.lock
This adds the [gatsby-plugin-sitemap](https://www.gatsbyjs.org/packages/gatsby-plugin-sitemap/) with the default configuration. 
sitemap can be seen [here](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/sitemap.xml).
=> add sitemap.xml plugin

packages/documentation/src/components/seo.js, packages/documentation/src/layouts/layout.js
implements some of the recommendations from here: https://community.algolia.com/docsearch/recommended-configuration.html
=> add docsearch stuff

packages/formation-react/package.json, packages/formation-react/src/components/MegaMenu/MegaMenu.jsx
=> 17320 mega menu ie 11 broken

packages/formation-react/package.json, packages/formation-react/src/components/MegaMenu/SubMenu.jsx
Ticket - https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17510
=> [MegaMenu] Lowercase the "a" in "View All in [hub name]"

packages/documentation/src/layouts/layout.js, packages/documentation/src/sidebar.js, packages/vagov-eslint/.eslintignore
- add rule to ignore built resources in formation-react
- fix linting issues
=> ignore built assets in formation react; fix linting errors

packages/documentation/yarn.lock, packages/vagov-eslint/.eslintrc, packages/vagov-eslint/package.json, yarn.lock
Not a whole lot going on here, just updating React so that the unit tests and gatsby use the same version as vets-website will use.
=> Update React, add hooks linting

packages/formation/package.json, packages/formation/sass/base/_b-variables.scss, packages/formation/sass/full.scss
verified locally against vets-website 
new bundle ---> [formation.zip](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/files/3040709/formation.zip)
=> move asset paths into variables

packages/documentation/src/pages/architecture/teamsite.mdx, packages/documentation/src/sidebar.js
=> 17652 document teamsite architecture

packages/formation/package.json
Version bump for the JavaScript stuff for Formation
=> Formation Version Bump JavaScript

packages/documentation/gatsby-config.js
=> update documetnation site title

packages/documentation/gatsby-config.js, packages/documentation/src/pages/platform/tools/feature-flags.mdx, packages/documentation/yarn.lock
Documentation that goes along with https://github.com/department-of-veterans-affairs/vets-website/pull/10016
=> Add docs for metalsmith flags

packages/documentation/package.json, packages/formation/package.json
Just a version bump to publish the full width alerts
=> version bump 6.2.5

package.json, packages/formation/js/accordion.js, packages/formation/js/index.js, packages/formation/package.json
When adding the formation.js there is a problem with React components click events and the events that are created with this code. We need to check whether an element already has a click event assigned to it and not run the accordion code if it does. This was discovered when implementing it on vets-website.
=> Fix Accordion Click event collision: Bug/18359

packages/documentation/src/pages/forms/about-the-schema-and-uischema-objects.mdx, packages/documentation/src/pages/forms/available-features-and-usage-guidelines.mdx, packages/documentation/src/pages/forms/available-widgets.mdx, packages/documentation/src/pages/forms/common-patterns-for-building-forms.mdx, packages/documentation/src/pages/forms/component-hierarchy.md, packages/documentation/src/pages/forms/config-options.md, packages/documentation/src/pages/forms/creating-a-form-config-file.md, packages/documentation/src/pages/forms/creating-custom-fields-and-widgets.md, packages/documentation/src/pages/forms/form-tutorial-advanced.mdx, packages/documentation/src/pages/forms/form-tutorial-basic.mdx, packages/documentation/src/pages/forms/form-tutorial-intermediate.mdx, packages/documentation/src/pages/forms/forms-in-production.mdx, packages/documentation/src/pages/forms/index.mdx, packages/documentation/src/pages/getting-started/workflow/write.mdx, packages/formation-react/src/components/AdditionalInfo/AdditionalInfo.mdx, packages/formation-react/src/components/AlertBox/AlertBox.mdx, packages/formation-react/src/components/CollapsiblePanel/CollapsiblePanel.mdx, packages/formation-react/src/components/ErrorableFileInput/ErrorableFileInput.mdx, packages/formation-react/src/components/MegaMenu/MegaMenu.mdx
will add the front matter for the platform and documentation guide in a separate PR
=> 18217 forms system search index

packages/formation/package.json
Forgot to do a version bump for the accordion fix.
=> version bump

packages/documentation/package.json, packages/formation/package.json, packages/formation/sass/modules/_m-nav-sidebar.scss
This PR adds missing properties and fixes the bug I described [here](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/106#issuecomment-491319506)
=> add missing sidenav css

packages/formation/__tests__/js/additional-info/additional-info.test.js, packages/formation/js/additional-info.js, packages/formation/js/index.js
- migrates additional info component from vets-website
- vets-website [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/10112)
=> 15167 additional info component

packages/documentation/src/pages/getting-started/common-tasks/previewing-changes.md
=> fix typos in `previewing-changes

packages/documentation/src/pages/platform/tools/feature-flags.mdx, packages/formation-react/package.json
- add overview / instructions for using release toggles
=> update feature toggle documentation

packages/formation/package.json, packages/formation/sass/utilities/_border.scss
increment package version for npm release
=> Issue 161: Increment formation version for npm release

packages/formation-react/package.json
- bump formation version to match published version
=> bump for e2e test fix

packages/documentation/src/pages/platform/front-end-standards/security.mdx, packages/documentation/src/sidebar.js, packages/documentation/yarn.lock
- add security document  to sidebar 
- update packages
=> add security to sidebar; update packages

packages/accessible-react-app/README.md
Updating the links to clone the repo, and removing the `$ yarn lint` command.
=> Update AnyCorp readme

packages/accessible-react-app/package.json, packages/accessible-react-app/src/css/forms.css, packages/accessible-react-app/src/css/global.css, packages/accessible-react-app/src/css/helpers.css, packages/accessible-react-app/src/css/layout.css, packages/accessible-react-app/src/css/main.css, packages/accessible-react-app/src/css/typography.css, packages/accessible-react-app/src/css/variables.css, packages/accessible-react-app/src/js/components/PrimaryNav.js, packages/accessible-react-app/src/js/pages/Feedback.js, packages/accessible-react-app/src/js/pages/Home.js, packages/accessible-react-app/src/js/routing/Routes.js, packages/accessible-react-app/yarn.lock
Several teams have asked for a modal dialog to be added to the AnyCorp learning tool to illustrate requirements to use this UI pattern accessibly. I used the [React Modal](https://github.com/reactjs/react-modal) because it is well supported and captures all of the accessibility features I want.
* Manual testing with VoiceOver + Safari, JAWS + Chrome, NVDA + Firefox
* Keyboard testing to determine focus management, focus return on close, and proper close button
---
=> AnyCorp - Adding a React Modal view

packages/documentation/src/pages/getting-started/internal-tools.mdx
Update internal tools access docs.
=> Update internal tool access docs

packages/formation-react/src/components/ErrorableTextInput/ErrorableTextInput.mdx
Fix a documentaiton error
None
=> Fix ErrorableTextInput code example

packages/formation-react/package.json, packages/formation-react/src/components/modal/Modal.jsx
This will fix a bug in veterans website caused by modal component
https://github.com/department-of-veterans-affairs/va.gov-team/issues/2427
=> Remove setState from unmount

packages/documentation/src/pages/platform/tools/feature-toggles.mdx
updated content of feature toggle documentation.
none, text only chagnes
=> updated feature toggle documentation

packages/formation-react/package.json, packages/formation-react/src/components/AlertBox/AlertBox.jsx
Fix issue that made unit tests in DowntimeMessage fail.
=> Fix error alertbox

packages/accessible-react-app/src/css/layout.css, packages/accessible-react-app/src/index.js, packages/accessible-react-app/src/js/components/Main.js, packages/accessible-react-app/src/js/components/PrimaryNav.js, packages/accessible-react-app/src/js/components/logos/AnyCorp.js, packages/accessible-react-app/src/js/layout/Layout.js, packages/accessible-react-app/src/js/pages/About.js, packages/accessible-react-app/src/js/pages/Feedback.js, packages/accessible-react-app/webpack.dev.config.js
The AnyCorp app is a training application to help developers and designers build accessible React applications. I've added some comments and HTML changes to help developers identify code specific to these goals.
* Ran the app locally. These changes are mostly formatting and adding comments for front-end teams to see "checkpoints" for coding practices related to React and accessibility.
=> Adding SVG a11y updates, front-end comments

packages/documentation/src/pages/platform/front-end-standards/manual-reviews.mdx, packages/documentation/src/sidebar.js
I updated the title of this doc to indicate the initial code quality review is automated. I also tried to clarify what actions the user can take.
=> Kristinagore review triggers

packages/documentation/src/pages/forms/available-widgets.mdx
Fix broken links on https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/available-widgets/#arraycountwidget
CI
=> Fix broken links

packages/documentation/src/pages/getting-started/common-tasks/new-application.mdx
I was perusing the documentation yesterday when I found that I missed a spot.
=> Reference the registry.json instead of the manifest file

packages/documentation/src/pages/forms/creating-a-form-config-file.md
=> Fix broken link

packages/documentation/src/pages/getting-started/index.mdx
I made some updates to this page based on observing Mike Chelen's walkthrough this morning. Let me know if you think they make sense/are accurate. Thanks!
=> Update from walkthrough observation

packages/documentation/src/pages/forms/form-tutorial-advanced.mdx, packages/documentation/src/pages/forms/form-tutorial-basic.mdx, packages/documentation/src/pages/forms/form-tutorial-intermediate.mdx, packages/documentation/src/pages/forms/save-in-progress.mdx, packages/documentation/src/sidebar.js
=> Kristinagore patch 1

packages/formation-react/package.json
Bumping version of formation-react so the Telephone widget will be available for use.
After merging, it will need to be published to npm
N/A
N/A
=> Formation-react v5.3.0

packages/documentation/README.md
simplify steps for token creation / usage
=> add token management summary

packages/formation-react/src/components/AlertBox/AlertBox.jsx
https://github.com/department-of-veterans-affairs/va.gov-team/issues/9124
=> add role="alert" to AlertBoxes for Accessibility Recommendations

README.md
Add link to formation contrib guide
=> Add link to formation contrib guide

packages/formation/package.json
bump version for changes in https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/314
=> Update formation to 6.9.3

packages/documentation/src/components/pageFooter/Components.jsx, packages/documentation/src/components/pageFooter/Documentation.jsx, packages/documentation/src/components/pageFooter/PageFooter.jsx, packages/documentation/src/layouts/SidebarLayout.jsx, packages/documentation/src/sidebar.js
See ticket [#9533](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9533) for description
Locally
=> Docs: add "Edit this page in Github" link

packages/documentation/src/components/pageFooter/Documentation.jsx
This PR fixes an error on the `Edit this page on GitHub` link caused by an extra `/` in path due to refresh in the browser
Locally
=> Fix Documentation extra / on link

packages/formation-react/package.json
=> Kelsonic 10885 banners

README.md
lerna term for these is "package"
=> lerna terminology

packages/documentation/src/pages/getting-started/workflow/review.mdx
=> update broken link

packages/formation-react/package.json, packages/formation-react/src/components/Telephone/Telephone.jsx, packages/formation-react/src/components/Telephone/Telephone.mdx, packages/formation-react/src/components/Telephone/Telephone.unit.spec.jsx
**Issue:** https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/341
This PR adds some additional TTY numbers.
N/A
N/A
=> Create initial boilerplate for additional TTY numbers

packages/documentation/src/pages/forms/save-in-progress.mdx
Added note to address https://github.com/department-of-veterans-affairs/va.gov-team/issues/10863
=> Fix for issue 10863

packages/documentation/src/pages/documentation-guide/index.mdx
=> add and clarify links for both doc package & parent repo

packages/documentation/README.md
=> link to root repo setup docs

packages/formation-react/package.json, packages/formation-react/src/components/AlertBox/AlertBox.jsx
This reverts commit 82166c14b685817a38a9fba0663b84afb0e28abc.
Closes https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/issues/362
None.
N/A
=> Revert "add role="alert" (#309)"

packages/documentation/src/pages/getting-started/common-tasks/new-widget.mdx
Clarifies how to get the `static-pages` bundle on the page.
=> Widget documentation update

packages/documentation/src/pages/forms/config-options.md
Update form config docs to include title function.
Related:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/12767
- https://github.com/department-of-veterans-affairs/vets-website/pull/13998
N/A
N/A
=> formConfig title function

packages/formation-react/package.json, packages/formation-react/src/components/Telephone/Telephone.jsx
Noticed the global help desk phone number was a dead end. Added the new updated phone number
Slack conversation for reference [Slack conversation](https://dsva.slack.com/archives/CBU0KDSB1/p1600454267062300?thread_ts=1600453407.058400&cid=CBU0KDSB1)
=> Update global help desk phone number

packages/documentation/src/pages/getting-started/common-tasks/debugging-tests.mdx
=> include new --log-level flag

packages/formation-react/package.json
=> bumped minor version number

packages/formation-react/package.json, packages/formation-react/src/components/Telephone/Telephone.jsx, packages/formation-react/src/components/Telephone/Telephone.mdx
Added DMC phone numbers to contact list to support the use of the `<Telephone/>` component for debt letters
=> Add dmc phone numbers to contact list

packages/formation-react/.storybook/main.js, packages/formation-react/.storybook/preview.js, packages/formation-react/package.json, packages/formation-react/scripts/build.js, packages/formation-react/src/components/AlertBox/AlertBox.stories.jsx
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/15210
This is intended for local development only right now. Publishing the Storybook will come later.
Tested the Storybook locally.
=> Add Storybook to formation-react for development

packages/documentation/src/pages/forms/config-options.mdx
Documentation for the new `saveInProgress` `formConfig` property introduced in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/14468).
=> Add saveInProgress documentation

packages/formation-react/src/components/AcceptTermsPrompt/AcceptTermsPrompt.jsx, packages/formation-react/src/components/AcceptTermsPrompt/AcceptTermsPrompt.mdx, packages/formation-react/src/components/AcceptTermsPrompt/AcceptTermsPrompt.stories.jsx
Created story for AcceptTermsPrompt component | closes [#15402](https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/15402)
=> 15402: Storybook Component - AcceptTermsPrompt

packages/formation-react/src/components/Breadcrumbs/Breadcrumbs.jsx, packages/formation-react/src/components/Breadcrumbs/Breadcrumbs.stories.jsx
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/15404
Tested the story locally.
=> Breadcrumbs story

packages/formation-react/src/components/CollapsiblePanel/CollapsiblePanel.jsx, packages/formation-react/src/components/CollapsiblePanel/CollapsiblePanel.stories.jsx
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/15405
Tested the stories locally. I added the optional chaining to the `window.VetsGov?.scroll` statement because that doesn't exist in Storybook and it didn't make sense to hack it in there.
**Default**
**Start Open**
**Borderless**
=> CollapsiblePanel stories

packages/formation-react/src/components/DropDownPanel/DropDownPanel.jsx, packages/formation-react/src/components/DropDownPanel/DropDownPanel.stories.jsx
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/15406
Tested the stories locally.
=> DropDownPanel stories

packages/formation-react/package.json, packages/formation-react/src/components/ErrorableTextInput/ErrorableTextInput.jsx
=> Fix errorable text input

packages/formation-react/src/components/ErrorableFileInput/ErrorableFileInput.stories.jsx
Created story for ErrorableFileInput component | closes [#15411](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15411)
=> 15411: Storybook Component - ErrorableFileInput

.gitignore, packages/formation-react/.gitignore, packages/formation-react/README.md, packages/formation-react/scripts/build.js, packages/formation-react/src/components/ErrorableCheckboxGroup/ErrorableCheckboxGroup.stories.jsx, packages/formation-react/src/components/ErrorableFileInput/ErrorableFileInput.stories.jsx
Just a few minor quality-of-life improvements.
=> Miscellaneous updates to formation-react

packages/formation-react/src/components/Pagination/Pagination.jsx, packages/formation-react/src/components/Pagination/Pagination.stories.jsx
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/15429
Tested locally on Storybook
=> Pagination stories

packages/formation-react/src/components/LoadingIndicator/LoadingIndicator.jsx, packages/formation-react/src/components/LoadingIndicator/LoadingIndicator.stories.jsx
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/15424
Tested locally on Storybook
*Without message*
*With message*
=> LoadingIndicator stories

packages/formation-react/src/components/Modal/Modal.stories.jsx
closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/15427
Tested locally in Storybook
**Default**
...and many more...
=> Add Modal stories

packages/formation-react/src/components/OMBInfo/OMBInfo.jsx, packages/formation-react/src/components/OMBInfo/OMBInfo.stories.jsx
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/15428
Tested locally on Storybook
**Closed modal**
**Open modal**
=> OMBInfo stories

packages/formation-react/src/components/ErrorableRadioButtons/ErrorableRadioButtons.jsx, packages/formation-react/src/components/ErrorableRadioButtons/ErrorableRadioButtons.stories.jsx
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/15414
Tested locally with Storybook.
**Nothing selected**
**Option selected**
**Option selected with expanded content**
**Invalid option selected**
=> ErrorableRadioButtons stories

packages/formation-react/src/components/ExpandingGroup/ExpandingGroup.jsx, packages/formation-react/src/components/ExpandingGroup/ExpandingGroup.stories.jsx
Add some stories for `<ExpandingGroup />`
=> Expanding group story

packages/formation-react/src/components/IconHelp/IconHelp.jsx, packages/formation-react/src/components/IconHelp/IconHelp.stories.jsx
=> Icon help story

packages/formation-react/src/components/IconSearch/IconSearch.jsx, packages/formation-react/src/components/IconSearch/IconSearch.stories.jsx
Adds story for `<IconSearch />`
=> Icon search story

packages/formation-react/src/components/HelpMenu/HelpMenu.jsx, packages/formation-react/src/components/HelpMenu/HelpMenu.stories.jsx
Adds a story for `<HelpMenu />`
=> Help menu story

packages/formation-react/src/components/IconUser/IconUser.stories.jsx
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/15423
=> IconUser stories

packages/formation-react/src/components/ProgressBar/ProgressBar.jsx, packages/formation-react/src/components/ProgressBar/ProgressBar.stories.jsx
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/15431
=> ProgressBar stories

packages/formation-react/src/components/MaintenanceBanner/MaintenanceBanner.jsx, packages/formation-react/src/components/MaintenanceBanner/MaintenanceBanner.stories.jsx
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/15425
=> MaintenanceBanner stories

packages/formation-react/src/components/ProgressButton/ProgressButton.jsx, packages/formation-react/src/components/ProgressButton/ProgressButton.stories.jsx
Closese https://github.com/department-of-veterans-affairs/va.gov-team/issues/15432
=> ProgressButton stories

packages/formation-react/src/components/PrivacyAgreement/PrivacyAgreement.jsx, packages/formation-react/src/components/PrivacyAgreement/PrivacyAgreement.stories.jsx
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/15430
=> PrivacyAgreement stories

packages/formation-react/.storybook/main.js, packages/formation-react/.storybook/preview.js, packages/formation-react/package.json
Adds an HTML section to the addons panel in Storybook.
=> HTML addon for Storybook

packages/formation-react/src/components/SegmentedProgressBar/SegmentedProgressBar.stories.jsx
Add a story for `<SegmentedProgressBar />`.
=> Segmented progress bar story

packages/formation-react/src/components/Telephone/Telephone.jsx, packages/formation-react/src/components/Telephone/Telephone.stories.jsx, packages/formation-react/src/components/Telephone/contacts.js
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/15438
Tested locally on Storybook.
**Default**
**Display only**
**Contacts list in `Docs`**
=> Telephone stories

packages/formation-react/src/components/SearchMenu/SearchMenu.jsx, packages/formation-react/src/components/SearchMenu/SearchMenu.stories.jsx
https://github.com/department-of-veterans-affairs/va.gov-team/issues/15434
**Closed**
**Open**
**Note:** The styling for this component is [only found in `vets-website`](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/sass/modules/_m-vet-nav.scss#L427-L447), so it's not showing up here properly. We'll need to either move the styling into `formation` or move the component out of `formation-react`.
=> SearchMenu stories

packages/formation-react/src/components/SystemDownView/SystemDownView.jsx, packages/formation-react/src/components/SystemDownView/SystemDownView.stories.jsx
https://github.com/department-of-veterans-affairs/va.gov-team/issues/15437
=> SystemDownView stories

packages/formation-react/src/components/EmergencyBanner/EmergencyBanner.stories.jsx, packages/formation-react/src/components/ErrorableCheckbox/ErrorableCheckbox.stories.jsx, packages/formation-react/src/components/ErrorableCheckboxGroup/ErrorableCheckboxGroup.stories.jsx, packages/formation-react/src/components/ErrorableDate/ErrorableDate.stories.jsx, packages/formation-react/src/components/ErrorableFileInput/ErrorableFileInput.stories.jsx, packages/formation-react/src/components/ErrorableMonthYear/ErrorableMonthYear.stories.jsx, packages/formation-react/src/components/ErrorableNumberInput/ErrorableNumberInput.stories.jsx, packages/formation-react/src/components/ErrorableRadioButtons/ErrorableRadioButtons.stories.jsx, packages/formation-react/src/components/ErrorableSelect/ErrorableSelect.stories.jsx, packages/formation-react/src/components/ErrorableTextArea/ErrorableTextArea.stories.jsx, packages/formation-react/src/components/ErrorableTextInput/ErrorableTextInput.stories.jsx, packages/formation-react/src/components/IconBase/IconBase.stories.jsx, packages/formation-react/src/components/IconHelp/IconHelp.stories.jsx, packages/formation-react/src/components/IconSearch/IconSearch.stories.jsx, packages/formation-react/src/components/IconUser/IconUser.stories.jsx, packages/formation-react/src/components/MaintenanceBanner/MaintenanceBanner.stories.jsx, packages/formation-react/src/components/PromoBanner/PromoBanner.stories.jsx
Groups some of the stories into logical sections.
=> Group stories

packages/documentation/src/pages/getting-started/index.mdx
Update node to 14.15.0 in the node setup documentation
=> Update node to 14.15.0

packages/documentation/src/pages/getting-started/index.mdx
=> Update yarn version in getting started doc

packages/documentation/src/pages/forms/about-the-schema-and-uischema-objects.mdx
Adding documentation for the change from this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/14802)
=> List loop scrolling config

packages/formation-react/package.json
=> Update to Storybook 6.1.1

packages/formation-react/.storybook/main.js, packages/formation-react/.storybook/preview.js, packages/formation-react/package.json, packages/formation-react/src/components/AlertBox/usage.stories.mdx, packages/formation-react/src/components/Breadcrumbs/Breadcrumbs.jsx, packages/formation-react/src/components/Breadcrumbs/usage.stories.mdx, packages/formation-react/src/components/CollapsiblePanel/static-markup.stories.js, packages/formation-react/src/components/CollapsiblePanel/usage.stories.mdx, packages/formation-react/src/components/ProgressBar/ProgressBar.stories.jsx, packages/formation-react/src/components/ProgressButton/ProgressButton.stories.jsx, packages/formation-react/src/components/PromoBanner/usage.stories.mdx, packages/formation-react/src/components/SegmentedProgressBar/SegmentedProgressBar.stories.jsx, packages/formation-react/src/components/Table/usage.stories.mdx, packages/formation-react/stories/README.md, packages/formation-react/stories/address-block.stories.mdx, packages/formation-react/stories/buttons.stories.mdx, packages/formation-react/stories/featured-content.stories.mdx, packages/formation-react/stories/form-controls.stories.mdx, packages/formation-react/stories/horizontal-rules.stories.mdx, packages/formation-react/stories/labels.stories.mdx, packages/formation-react/stories/process-list.stories.mdx, packages/formation-react/stories/sidenav.stories.mdx
I pulled the designer-facing documentation into Storybook.
Organization TBD, but that can be cleaned up in another PR.
It's probably better to run storybook locally and see the changes there. :see_no_evil:
=> Designer-facing documentation in storybook

packages/documentation/src/pages/getting-started/common-tasks/new-end-to-end-test.mdx
Fix to requirements section of end-to-end testing documentation, per a Slack discussion on #vsp-testing-team-tools. 
Revised documentation to properly reflect required not recommended best practices.
- [ x ] Update documentation to properly reflect requirements not recommendations.
- [x ] Changes have been tested in vets-website
- [x ] Changes have been tested in IE11, if applicable
- [ x] Documentation has been updated, if applicable
- [N/A ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
=> Update Requirements Section of End-to-End

packages/formation/package.json
I forgot to do this as part of #562  :upside_down_face:
=> Bump version for publishing

packages/formation-react/README.md
We've moved the repo. This PR points to its new home.
=> Replace README contents; link to component-library

packages/formation/package.json, packages/formation/sass/full.scss, packages/formation/sass/modules/_m-action-link.scss, packages/formation/sass/site/site.scss
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/19667
Visual. See https://github.com/department-of-veterans-affairs/component-library/pull/51
=> Add action link styling

packages/documentation/src/pages/getting-started/workflow/deploy.mdx
Updated rollback documentation.
Confirmed correctness with Ops
=> Updated vets-website rollback documentation

packages/documentation/src/pages/getting-started/workflow/deploy.mdx
Updated docs for creating a release and hotfix
Had to do one!
=> Added release and hotfix documentation

packages/documentation/src/pages/getting-started/workflow/deploy.mdx
=> update slack channel name

packages/documentation/src/pages/getting-started/workflow/deploy.mdx
=> add note about permissions, update terminology

packages/formation/package.json, packages/formation/sass/modules/_m-form-elements.scss
for info, see https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/591
Opening this PR to get around codeowners issue
=> Radio button cursor

packages/documentation/src/pages/getting-started/workflow/deploy.mdx
Adding documentation about what to do with flaky unit tests per request: https://dsva.slack.com/archives/G01M8VD9USC/p1617131259099400?thread_ts=1617119310.093600&cid=G01M8VD9USC
=> Updated deployment docs with unit test procedures

packages/documentation/src/pages/getting-started/workflow/deploy.mdx
=> link to Platform deployment policy

packages/documentation/src/pages/getting-started/workflow/deploy.mdx
Adding documentation for a staging deployment.
=> added staging deployment docs

packages/documentation/src/pages/platform/tools/feature-toggles.mdx
=> remove extraneous html

packages/documentation/src/pages/getting-started/workflow/deploy.mdx
Added content onlydeployment schedule to docs
Schedule pulled from https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/jenkins-vetsgov/seed_job.groovy#L309
=> Added content only deployment schedule to docs

packages/documentation/src/pages/getting-started/workflow/deploy.mdx
=> update slack channel name and links

packages/documentation/src/scss/_dashboard.scss
This PR fixes the font size int the tables which is different locally and live. It also fixes the image size in small devices
Locally
=> Minor Dashboard CSS changes

packages/documentation/src/pages/frontend-support-dashboard/app.jsx, packages/documentation/src/scss/_dashboard.scss
This PR will make the tables full width
Locally
=> Dashboard full width

packages/documentation/src/components/dashboard/definitions/constants.jsx
Added https URLs for vets-website [app buckets](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/constants/buckets.js)
=> fixed bucket URLs to match content-build

packages/documentation/src/pages/getting-started/common-tasks/new-unit-test.mdx
This PR updates the existing documentation for our new unit-test best practices to encourage the use of React Testing Library in place of Enzyme, and provide examples on how to do so.
N/A
N/A
=> Update Unit Test Best Practices

packages/documentation/src/pages/getting-started/index.mdx
We updated the default build command, this is the accompanying documentation.
=> updated default build command for vets-website

packages/documentation/src/pages/getting-started/workflow/deploy.mdx
Updated docs for dev deployments
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/238
=> Added documentation for dev deployments

packages/documentation/src/pages/platform/architecture/reverse-proxy.mdx, packages/documentation/src/sidebar.js
Adding documentation for revproxy based off @jhonnyoddball's documentation from content-build separation https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/infrastructure/reverse_proxy.md
=> Added Revproxy documentation

packages/documentation/src/pages/getting-started/index.mdx
Added more detailed guidance on working with CSS/JS updates in vets-website that need to be viewed in content-build.
=> Updated local setup docs

packages/formation/package.json
Increments the version of `formation`. This PR will be followed up with an `npm publish` in the formation directory + a follow-up PR in `vets-website` that increments the `formation` version.
=> Increment formation version

packages/documentation/src/pages/getting-started/index.mdx
Updating watch documentation to match functionality in PR https://github.com/department-of-veterans-affairs/vets-website/pull/17490
=> Updated yarn watch documentation

packages/documentation/src/pages/getting-started/common-tasks/new-unit-test.mdx
Adds a link to the recording of the Front End Unit Test Best Practices Brown Bag Training from June 17th, 2021 to the unit testing documentation
=> add recording of unit testing best practices session

packages/documentation/src/pages/platform/tools/feature-toggles.mdx
See this slack thread for a discussion about using a test user for manipulating feature toggles in Dev
https://dsva.slack.com/archives/CBU0KDSB1/p1621362206028900
=> Update feature toggles documentation

packages/documentation/src/pages/getting-started/workflow/deploy.mdx
Updating notes per [slack conversation](https://dsva.slack.com/archives/C01512KN35G/p1626724042261200?thread_ts=1626721392.255400&cid=C01512KN35G)
=> Added deployment notes

packages/documentation/gatsby-node.js, packages/documentation/src/components/dashboard/CommitsTable.jsx, packages/documentation/src/components/dashboard/DashboardDataFetch.jsx, packages/documentation/src/components/dashboard/Reducer.jsx, packages/documentation/src/components/dashboard/definitions/constants.jsx, packages/documentation/src/layouts/SidebarLayout.jsx, packages/documentation/src/pages/frontend-support-dashboard/app.jsx, packages/documentation/src/pages/frontend-support-dashboard/unit-test-coverage-report/app.jsx, packages/documentation/src/pages/index.jsx, packages/documentation/src/pages/unit-test-coverage-report/app.jsx, packages/documentation/src/scss/_dashboard.scss, packages/documentation/src/scss/_sidebar.scss, packages/documentation/src/scss/_site-content.scss, packages/documentation/src/sidebar.js
**NOT READY TO MERGE UNTIL AFTER DAILY PROD DEPLOY ON JULY 21**
This PR adds two things:
1. A sidebar for the Frontend Support Dashboard
2. The `vets-website` Unit Test Coverage Report
Visual testing using coverage report from Staging build
**Frontend Support Dashboard Deploy Status with sidebar**
**Unit Test Coverage Report**
=> 184 unit test coverage dashboard

packages/documentation/src/components/dashboard/definitions/constants.jsx, packages/documentation/src/pages/frontend-support-dashboard/unit-test-coverage-report/app.jsx, packages/documentation/src/pages/frontend-support-dashboard/unit-test-coverage-report/test-coverage-report.json
Update to use a static coverage report file.
=> Test coverage report fix

packages/formation/sass/modules/_m-megamenu.scss
https://github.com/department-of-veterans-affairs/va.gov-team/issues/25659
This change is in conjunction with changes to
content-build: https://github.com/department-of-veterans-affairs/content-build/pull/420
vets-website: https://github.com/department-of-veterans-affairs/vets-website/pull/18116
**Updated PR to allow this change to merge independently and prior to the other 2 prs.**
local
=> use mega-menu class for styles

packages/formation/sass/core.scss, packages/formation/sass/utilities/_position.scss
@mpelzsherman brought up a good point about having position utility classes available: https://github.com/department-of-veterans-affairs/content-build/pull/505#discussion_r701202832
=> Add position utility classes

packages/formation/package.json
Adds position utility classes from PR: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/671/files
=> Bumped formation to 6.17.0 for new feature: position utility classes

packages/documentation/src/components/dashboard/definitions/constants.jsx
Pointing this to the correct bucket.
=> Updated BUILD.txt for dev

packages/formation/sass/modules/_m-responsive-tables.scss
Add a couple of classes to `table.response` here per @bkjohnson - https://github.com/department-of-veterans-affairs/vets-website/pull/18726#discussion_r714379165
=> Add sort classes to table

packages/documentation/src/pages/frontend-support-dashboard/unit-test-coverage-report/app.jsx, packages/documentation/src/pages/frontend-support-dashboard/unit-test-coverage-report/archive/2021-10-04-test-coverage-report.json, packages/documentation/src/pages/frontend-support-dashboard/unit-test-coverage-report/test-coverage-report.json
=> Updated coverage report

.github/workflows/continuous-integration.yml, .github/workflows/install/action.yml
[Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33419) associated with PR
This PR is adding CI workflow in Github Actions from Jenkins
Latest workflow run
=> Github Actions -- Continuous Integration

packages/documentation/gatsby-node.js, packages/documentation/src/pages/frontend-support-dashboard/lighthouse-performance-report/app.jsx, packages/documentation/src/pages/frontend-support-dashboard/lighthouse-performance-report/lighthouse-report.json, packages/documentation/src/pages/frontend-support-dashboard/unit-test-coverage-report/app.jsx, packages/documentation/src/pages/index.jsx, packages/documentation/src/sidebar.js
[Ticket](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/28386) associated with PR
This PR creates a dashboard for lighthouse report that is generated from daily lighthouse scan in [vets-website](https://github.com/department-of-veterans-affairs/vets-website/actions/workflows/daily-lighthouse-scan.yml)
Locally (see screenshot below)
=> FE Lighthouse dashboard

packages/documentation/src/pages/forms/available-features-and-usage-guidelines.mdx
Part of closing: https://github.com/department-of-veterans-affairs/va.gov-team/issues/32864
Complimentary PR: https://github.com/department-of-veterans-affairs/vets-website/pull/19694
=> Documentation Update for Segmented Progress Bar Web Component

packages/documentation/src/pages/frontend-support-dashboard/lighthouse-performance-report/app.jsx, packages/documentation/src/pages/index.jsx, packages/documentation/src/sidebar.js
Updated labels here to clear up lighthouse confusion
=> Updated Lighthouse Performance report labelling

packages/documentation/src/pages/frontend-support-dashboard/cross-app-import-report/app.jsx, packages/documentation/src/pages/frontend-support-dashboard/cross-app-import-report/archive/2022-01-13-cross-app-imports.json
This PR updates the cross app import report. It looks like percentage of isolated increased a little bit.
Local testing
=> Update cross app import report

.github/workflows/continuous-integration.yml, Jenkinsfile
https://github.com/department-of-veterans-affairs/va.gov-team/issues/33419 associated
This PR enables deploy in Github Actions and removes from Jenkins
=> enable deploy to GHA and disable jenkins

.github/workflows/continuous-integration.yml
address this:
https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/runs/5323502371?check_suite_focus=true
yes
=> fix the credential-helper path

.github/workflows/continuous-integration.yml
fix this: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/runs/5324000975?check_suite_focus=true
=> try update token to password value to deploy

.github/workflows/continuous-integration.yml, Jenkinsfile
This PR turns on deploys in GitHub Actions. The correct credentials needed to be added.
Related ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/33419
=> Deploy from GitHub Actions

.github/workflows/continuous-integration.yml, Jenkinsfile
Reverts https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/768
=> Revert gha deploy

.github/workflows/continuous-integration.yml, Jenkinsfile
this adds the right path for ssm getparameter for the service account in use: svc-gha-frontendteam-user
tested build. Deploy can only be verified on commit
=> github token inclusion with right ssm

packages/formation/package.json
Bump Major Version
#774 and #761
=> BREAKING CHANGE: v7.0.0 Formation Major Version

.github/workflows/continuous-integration.yml
Update repo link in `Deploy` job.
=> Update repo link in deploy job

packages/documentation/gatsby-node.js, packages/documentation/src/components/dashboard/DashboardDataFetch.jsx, packages/documentation/src/components/dashboard/definitions/constants.jsx, packages/documentation/src/pages/frontend-support-dashboard/status/app.jsx, packages/documentation/src/pages/index.jsx, packages/documentation/src/sidebar.js
Adding this page to see if our CORS are set up correctly
Ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/177
=> Added service status check to dashboard

packages/documentation/src/pages/frontend-support-dashboard/lighthouse-performance-report/lighthouse-report.json
adds app name property (i.e. the name of the top-level folder in src/applications of `vets-website`) to entries in lighthouse-report.json so that the entries can be associated easily with the team that owns them inside the console ui front-end.
n/a
=> add app folder info to lighthouse-report.json for use in console ui

packages/formation/sass/full.scss, packages/formation/sass/site/site.scss
Remove Imports since file has been removed from build
=> 38305 Search Css Imports

.github/CODEOWNERS
Updating design system team codeowners
=> Update dst codeowners

packages/documentation/src/pages/getting-started/common-tasks/new-page.mdx
DO NOT MERGE UNTIL VAGOV-CONTENT DEFAULT BRANCH IS MAIN
=> update reference to vagov-content default branch

packages/formation/package.json, packages/formation/sass/base/_b-variables.scss
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/882
=> 882 Negative Margin Spacers Fix

packages/documentation/src/components/dashboard/definitions/constants.jsx, packages/documentation/src/pages/platform/site-structure/environments.mdx, packages/documentation/src/pages/platform/tools/downtime-notifications.mdx, packages/documentation/src/pages/platform/tools/feature-toggles.mdx
Updating references to vets-api per the migration plan.
department-of-veterans-affairs/va.gov-team#39205
=> Updated vets-api calls

packages/formation/package.json, packages/formation/sass/formation-overrides/elements/_typography.scss, packages/formation/sass/modules/_m-megamenu.scss
related ticket https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2909
related PR https://github.com/department-of-veterans-affairs/vets-website/pull/30089
=> Formation: Font normalization QA updates

packages/formation/README.md
Updating Formation README.md to remove straggler comment
=> update read me to remove test comment

packages/formation/package.json, packages/formation/sass/core.scss
Comment out border imports. css-library will supply these styles to vets-website
issue: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3199
local testing with verdaccio
no visual changes
=> comment out border utils import
