packages/formation/sass/modules/_m-megamenu.scss

This PR fixes an issue with the focus outline of the "View All in [hub name]" stretching beyond the width of the MegaMenu.
Ticket - https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14306

[MegaMenu] Fix outline on focus of "View All in [hub name]"

---

packages/formation-react/package.json
packages/formation-react/src/components/alerts/AlertBox/AlertBox.jsx
packages/formation-react/src/components/modal/Modal.jsx
packages/formation/package.json
packages/formation/sass/base/_b-mixins.scss
packages/formation/sass/modules/_m-alert.scss
packages/formation/sass/modules/_m-modal.scss
packages/formation/sass/shared-variables.scss

* Refactored alert modals to use alert classes.
* Support for 'continue' status for alert modals.
* Alerts and modals share common close button.
* Spacing changes for alerts (and alert modals) to more closely match design.
* Corrected `formation` peer dep version for `formation-react`.
> <img width="647" alt="screen shot 2019-02-25 at 8 29 50 pm" src="https://user-images.githubusercontent.com/1067024/53665051-51d10a00-3c38-11e9-94ea-2c07e8a710df.png">
> <img width="617" alt="screen shot 2019-02-25 at 12 39 54 pm" src="https://user-images.githubusercontent.com/1067024/53665139-8fce2e00-3c38-11e9-8d67-7bfc521c60b3.png">
> <img width="635" alt="screen shot 2019-02-25 at 8 29 26 pm" src="https://user-images.githubusercontent.com/1067024/53665099-73ca8c80-3c38-11e9-8402-7a9cf9ea9f11.png">
> …

Tweaks to alerts and alert modals

---

packages/documentation/src/components/sidebar/Sidebar.js

The url check in the Sidebar component doesn't work when there's a path prefix, so this loosens it in order to fix the live site.

Fix url check in Sidebar

---

packages/formation/package.json
packages/formation/sass/base/_b-variables.scss
packages/formation/sass/utilities/_background-color.scss
packages/formation/sass/utilities/_border.scss
packages/formation/sass/utilities/_color.scss

This PR will create a set of Sass variables for Hub colors that align with the naming conventions of all other colors in the design system. With this addition, front end developers will be able to use `color: $color-hub-healthcare` instead of `color: $indigo-cool-60`.

create contextual hub variable names

---

packages/formation/package.json
packages/formation/sass/core.scss
packages/formation/sass/modules/_m-external-link.scss

This PR will bring the CSS for the external link into Formation. 
After this PR is merged, there will be another PR for vets-website to remove the CSS and update the Formation version number.

bring CSS for external link into Formation css

---

packages/formation/package.json
packages/formation/sass/base/_b-breakpoints.scss
packages/formation/sass/base/_b-variables.scss

This PR will add some USWDS variables to Formation. 
With these additions, you can use the Formation Sass variables and functions without requiring USWDS as a dependency.

add missing uswds variables

---

packages/documentation/src/pages/architecture/http-headers.mdx

there's another ticket to add support for markdown slides but you can see a preview of the slides by pasting this into here: 
https://web.marp.app
if we decide to support slides / decks, interested to hear how we would like to structure them in the doc repo. we could duplicate the file, remove the slide specific markup, put a link to the deck in that file, and exclude the deck from the search indexing.

Add http headers deck

---

packages/formation/package.json
packages/formation/sass/utilities/_font-size.scss

This will add some extra classes to the font-size utility. The classes are redundant, but @1Copenut mentioned it would help developers choose the right utility class when change font sizes on headings while maintaining correct semantic level.

add heading levels to font size utilities

---

packages/formation-react/package.json
packages/formation-react/src/components/ErrorableRadioButtons/ErrorableRadioButtons.jsx

Found a bug where an extra `>` was getting prepended to labels in radio buttons.
Before:
After:

Remove greater than errorable radio mg

---

packages/formation/package.json
packages/formation/sass/_shame.scss

I noticed there is a ~10px difference in some of the grid padding on my sandbox site using only formation and va.gov. It _looks_ like this CSS can be removed safely because it is overwritten here: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/sass/merger.scss#L566
This pull request will help get Formation one step closer to providing samples for full page layouts that are equal to what is on va.gov.

remove some uswds grid padding

---

packages/documentation/src/pages/architecture/visual-regression-testing.mdx
packages/documentation/src/sidebar.js

- Add VRT docs
- I didn't test these instructions this week but they worked a couple of months ago when I was building the VRT for teamsites. 
- opted to leave the teamsite VRT instructions in the teamsite docs. we can reorganize or link later.

add visual regression testing doc

---

packages/formation/package.json
packages/formation/sass/layout/_flex-grid.scss

This PR addresses an issue with the full-width grid container using a `max-width` of `100rem`. 
This screenshot shows the change in effect in local development:

set full-width grid container max width

---

README.md

This update will remove the github.io URLs for design.va.gov, as well as the link to the legacy site. 
New update links to the repo for the documentation site as well.

update readme to reflect design.va.gov

---

package.json
packages/documentation/package.json
packages/formation/package.json
webpack.config.prod.js
yarn.lock

Formation.min.css does not include browser prefixes, which the `appearance` property is causing a display error on the select boxes
This takes the same configuration used on `vets-website`: https://github.com/department-of-veterans-affairs/vets-website/pull/9890
Here is a screenshot after testing locally:

add prefixes to formation.min.css with autoprefixer

---

packages/formation/__tests__/js/accordion/accordion.test.js
packages/formation/js/accordion.js
packages/formation/package.json

The script does not work on bordered accordions as they are coded in USWDS 1.x: 
There appears to be issues with traversing the DOM. Notice when I click the top set of accordions, the bottom set collapses.

Accordion errors in Formation 6.2.0: Bug/18077

---

packages/formation-react/package.json
packages/formation-react/src/components/AlertBox/AlertBox.jsx
packages/formation-react/src/components/AlertBox/AlertBox.mdx
packages/formation-react/src/components/AlertBox/AlertBox.unit.spec.jsx

Seemed like it should be possible to turn an AlertBox into its 'background only' variant without resorting to passing in a class name like I've had to do [here](https://github.com/department-of-veterans-affairs/vets-website/blob/d1afbcd92d91d4892469277ca1b96163f2781946/src/applications/personalization/dashboard/components/ManageYourVAHealthCare.jsx#L73) and [here](https://github.com/department-of-veterans-affairs/vets-website/blob/3e7daca36ae04b7263eb12f0d889c75f305391ed/src/applications/hca/containers/IntroductionPageGated.jsx#L96)

Add optional `backgroundOnly` prop to AlertBox

---

Jenkinsfile
babel.config.js
packages/formation-react/package.json
packages/formation-react/scripts/build.js
packages/formation/package.json
yarn.lock

When we updated the Babel config I accidentally carried over the `modules: false` option from the vets-website config, which is not what we want in this repo. That caused `imports` to stop being converted to `require`s.
To test this locally, you'll need to run the build command once with `BABEL_DISABLE_CACHE=1` set as an env variable.

Set Babel to transpile modules

---

packages/documentation/package.json
packages/formation/package.json
packages/formation/sass/base/_b-variables.scss

Cool blue variables were missing and causing errors in projects using formation when attempting to work with the sass variables in project files.

add cool blue variables

---

packages/documentation/src/components/Search.jsx

add lowercase transform to matching query filter

---

packages/documentation/package.json
packages/formation/package.json
packages/formation/sass/modules/_m-alert.scss

This PR will add the full-width alert (that appears below the nav bar) CSS to Formation. 
After this PR is merged and published to NPM, another PR will be made to `vets-website` removing the CSS from the `shame.scss` file and updating the formation version. 
Here is a screenshot of the alert with this work in place on localhost:
These alerts are now able to be placed on design.va.gov (screenshot of localhost)

add full-width version of alerts css to Formation

---

packages/formation-react/package.json
packages/formation-react/src/components/AlertBox/AlertBox.jsx
packages/formation-react/src/components/AlertBox/AlertBox.unit.spec.jsx

\[Companion to vet-website [PR10024](/department-of-veterans-affairs/vets-website/pull/10024) (Pass more descriptive aria-label string to AlertBox)\]
[16114](/department-of-veterans-affairs/vets.gov-team/issues/16114) - Change AlertBox aria attributes:
- Refactor close button aria-label to optionally accept a more descriptive string-value.
- Remove the aria-live attribute from outer element.  React removes the entire alert element when User clicks the close button, so this attribute (which announces inner-content updates) is moot.
Also bumped formation-react version to 4.4.3.

16114 dashboard homeless alert screenreader changes

---

packages/documentation/plugins/github-api-pages/github-pages.json
packages/documentation/src/layouts/external-layout.js

With the team repo re-org, some of the paths changed, which breaks some pages we're trying to pull in.

Fix the paths to team repo pages

---

packages/formation/js/accordion.js
packages/formation/js/index.js
packages/formation/js/sidenav.js

This is the same fix for https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/106. I found a bug. This should fix the issue with going from mobile to desktop. I also found a bug regarding multiple sidebar accordions being open when they shouldn't be.
Bug:
Fix:

add fix for sidebar scrolling and multiple open accordions

---

packages/formation/js/sidenav.js
packages/formation/package.json

After moving to formation.js for the sidebar, sidebar errors now break accordions, because they happen after the sidenav code.
This PR fixes a couple of the common errors:
http://sentry.vetsgov-internal/vets-gov/website-production/issues/60387/?query=is:unresolved
http://sentry.vetsgov-internal/vets-gov/website-production/issues/59485/?query=is:unresolved

Fix sidebar errors that break accordion

---

package.json
packages/formation-react/package.json
packages/formation-react/src/components/Pagination/Pagination.jsx

You can see this in the search app, or any other place that uses Pagination but does not use the ariaLabelSuffix prop. The component needs to print an empty string, not undefined, when that prop is not provided.

The Pagination component is writing "undefined" in the next/previous page aria-labels

---

packages/formation-react/package.json
packages/formation-react/src/components/CollapsiblePanel/CollapsiblePanel.jsx

Add a `borderless` propType to control whether the content panels have a border or not.

Add option to toggle borders in CollapsiblePanel

---

packages/documentation/package.json
packages/formation/package.json
packages/formation/sass/base/_va.scss

This PR will add support for styling `h2`s in featured content boxes. The styling simply removes the top margin. 
This should be included so that the proper semantic heading level can be applied.
Before:
After:

add h2 support in feature component

---

packages/formation/package.json
packages/formation/sass/modules/_m-loading-indicator.scss

Currently, the loading-indicator uses an animated SVG as its spinner. This isn't friendly with Internet Explorer or Edge - in those browsers, it's just a blue outline of a circle. This wasn't an issue before because most of the time the spinner was only shown for a split second. However, the new Community Cares functionality can take a full minute to load, and the broken SVG makes it appears that much more broken.
This PR proposes we switch to a CSS spinner. [transition](https://caniuse.com/#feat=css-transitions) appears to be supported by all of the browsers VA.gov supports.
Ticket - https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18818
Tested UX of Facility Locator
- Tested app booting up
- Tested queries

[Loading Indicator] Switch from SVG to CSS

---

packages/documentation/package.json
packages/formation/package.json
packages/formation/sass/base/_va.scss

This is a minor fix to the lead text `line-height` suggested by @rtwell.
What was happening is that the  `line-height` was computing to `30px` for this:
```
<div class="va-introtext">
<p>Some text</p>
</div>
```
But it would be `34px` for this:
```
<p class="va-introtext">Some text</p>
```
We want the `line-height` to be `34px`.  Looks like the paragraph's base styles were overriding the CSS in `va-introtext`, so this patch just reinforces that with some extra specificity.

fix lead line height

---

packages/formation-react/package.json
packages/formation-react/src/components/PromoBanner/PromoBanner.jsx
packages/formation-react/src/components/PromoBanner/PromoBanner.mdx
packages/formation-react/src/components/PromoBanner/PromoBanner.unit.spec.jsx
packages/formation/package.json
packages/formation/sass/full.scss
packages/formation/sass/modules/_m-promo-banner.scss
packages/formation/sass/site/site.scss

Formerly known in vets-website as an "announcement", this PR redesigns and implements a promo-banner component. 
There are three types of promo-banners, each with their own FA icon -
1. Announcement (this is why I changed the name)
2. News
3. Email Signup
Ticket - https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18175
Once this is ready, I'll update the vets-website PR to begin consuming the new `PromoBanner` component, https://github.com/department-of-veterans-affairs/vets-website/pull/10269.
- Locally tested in vets-website

Implement PromoBanner

---

packages/formation/package.json
packages/formation/sass/modules/_m-promo-banner.scss

Follow-up to https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/137 based on vets-website comment, https://github.com/department-of-veterans-affairs/vets-website/pull/10269#issuecomment-504101042.
This PR removes some padding-left on large/medium screens.
tested different screen sizes

[Promo-Banner] Remove padding-left on large screens

---

packages/formation/package.json
packages/formation/sass/modules/_m-promo-banner.scss

On medium-large screen sizes it looked like the close button was too close to the edge. This PR fixes that by just always allowing the padding around the close button. 
Resizing the browser over and over again

[Promo Banner] Always allow padding around close button

---

packages/documentation/src/scss/main.scss
packages/formation-react/src/components/MegaMenu/MegaMenu.mdx

I added some fixes to the MegaMenu doc. It was not rendering correctly due to missing SCSS. I also checked what dependancies were needed if anyone wanted to implement this on a brand new application. I know this might not be the future of the MegaMenu but I think it doesn't hurt to have it.
Local

add fixes to generate megamenu correctly on doc

---

packages/documentation/package.json
packages/formation/package.json
packages/formation/sass/utilities/_font-weight.scss

This will set the font-weight utility to be `400` instead of `300`. `300` is incorrect, and the but was not discovered most likely because of design.va.gov does not using the light version of Source Sans Pro, but VA.gov is using it.
Visible here: https://staging.va.gov/pittsburgh-health-care/health-services/

correct font-weight value for font utility

---

packages/formation-react/package.json
packages/formation-react/src/components/AlertBox/AlertBox.jsx
packages/formation-react/src/components/AlertBox/AlertBox.unit.spec.jsx

This adds a level prop to the alert box, so that you can control the heading level directly and avoid axe errors related to skipping heading levels in an html page (e.g. following an `h1` with an `h3`, instead of an `h2`).
Unit testing

Add level prop to AlertBox

---

packages/formation-react/package.json

Accidentally chose an already existing version for the previous AlertBox change

Bump version for level prop change

---

packages/formation/__tests__/js/accordion/accordion.test.js
packages/formation/js/accordion.js
packages/formation/package.json

Currently you can make accordions multiselectable by using `aria-multiselectable` on the main element. This is invalid aria markup that aXe throws errors on. This PR adds another attribute to trigger the same behavior that won't cause accessibility issues.
Testing in vets-website

Allow use of `data-multiselectable` in addition to incorrect aria attribute

---

packages/formation/package.json
packages/formation/sass/base/_b-mixins.scss

This came up while working on disabled button-links on the disability calculator, mentioned in this [ticket](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19143).
Buttons that are styled to look like links should be gray when disabled.
I tested this on the [disability calculator](https://staging.va.gov/disability/about-disability-ratings-beta/).

Add disabled state for buttons that are styled as links

---

packages/formation-react/package.json
packages/formation-react/src/components/ErrorableCheckbox/ErrorableCheckbox.jsx
packages/formation-react/src/components/ErrorableCheckbox/ErrorableCheckbox.mdx
packages/formation-react/src/components/ErrorableCheckbox/ErrorableCheckbox.unit.spec.jsx

[16156](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16156) - Add optional screen-reader support to read an external-heading instead of checkbox-label.
formation-react version bumped to 4.9.0 [minor update].
New unit-test added; All still passing (now 184 tests).

16156 - Add optional ariaLabelledBy prop to ErrorableCheckbox.

---

packages/formation-react/package.json
packages/formation-react/src/components/MegaMenu/Column.jsx

The second column of the Records section of the MegaMenu should have an empty space instead of a title. So, this PR makes the title optional.
Ticket - https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17695
Pointed local vets-website to MegaMenu of local design system

[MegaMenu] Make the column title optional

---

packages/formation-react/package.json

We need to update lodash to version 4.17.12 or later to fix a [vulnerability](https://www.npmjs.com/advisories/1065).
Copy of original ticket
department-of-veterans-affairs/va.gov-team#589
Current ticket with summary of necessary changes
department-of-veterans-affairs/va.gov-team#841
Linked to local build of vets-website and ran unit and E2E tests.

Updated lodash to resolve advisory 1065

---

packages/formation/sass/utilities/_border.scss

- adds breakpoint name to "border-bottom" classes
locally by pointing to local formation build in vets-website's package.json
1. used `medium-screen:vads-u-border-bottom--1px` on element I was attempting to add this to

Issue-161: add breakpoint name to "border-bottom" classes

---

packages/formation-react/package.json
packages/formation/js/accordion.js
packages/formation/package.json

Add custom click event to formation’s accordion-wrapper, to support [19247](/department-of-veterans-affairs/vets.gov-team/issues/19247)’s analytics requirements.
An upcoming static-page update for Disability Ratings has Google Analytics events specified to fire on expand/collapse of the Combined ratings table accordions. See this [ticket comment](/department-of-veterans-affairs/vets.gov-team/issues/19247#issuecomment-520847648).
Insights Team has since decided to capture accordion expand/collapse analytics site-wide, not just for the Disability Ratings page.  See this [ticket comment](/department-of-veterans-affairs/vets.gov-team/issues/19247#issuecomment-521237700).
Using browser dev-tools, verified custom click-event pushed to Google Analytic’s window.dataLayer upon clicking any …

19247 disability calculator analytics

---

packages/formation-react/package.json
packages/formation-react/src/components/MegaMenu/SubMenu.jsx

Currently, the text "View all in" in the `seeAllLink` is hard-coded. This PR removes that hard-coded text so that it can be changed.
_Motivation:_ The header of va.gov will soon be generated by Drupal, and the links coming from Drupal will need to contain "View all in." Without this change, the text would be repeated: "View all in View all in."
There is also a PR to update the `vagov-content` repo so that the megamenu fragment contains "View all in," to match the future Drupal data: https://github.com/department-of-veterans-affairs/vagov-content/pull/555
- Updated code in this repo locally.
- Ran `yarn build`.
- Moved this code to local vets-website installation.
- Built vets-website with local Drupal data.
- Confirmed visually that "View all in ..." was present. (See screenshot below.)

Remove megamenu "View all in" text

---

packages/formation-react/package.json
packages/formation-react/src/components/modal/Modal.jsx

Previously shift-tab only worked until focus reached the first
focusable element in the modal. Hitting shift-tab when focus was on the
first element in the modal resulted in effectively a no-op as focus was
programmatically set to the first focusable element. With this change a
shift-tab while the first element on the modal has focus will move focus
to the _last_ element in the modal, as you would expect.
Local in vets-website
**GIF showing ability to tab forwards and backwards within the modal correctly**

Fully enable shift-tabbing in Modal components

---

packages/documentation/src/pages/getting-started/common-tasks/analytics.mdx
packages/documentation/src/sidebar.js

We need a document regarding adding analytics to our front end so that external developers can know what to do when adding analytics to their feature or page.
Local Test

add doc on analytics

---

packages/documentation/src/pages/platform/tools/feature-flags.mdx

The documentation was out of date. This brings it back up to date.
N/A
N/A

Update the CMS feature flags documentation

---

packages/formation-react/package.json
packages/formation-react/src/components/PromoBanner/PromoBanner.jsx

The Proclamation PromoBanner on the website now (use Incognito tab if you cleared it already) opens a PDF file in the same tab, which is not ideal. We need a new prop to open it in a new tab.
Ticket - https://github.com/department-of-veterans-affairs/va.gov-team/issues/3212
Tested locally
N/A

[PromoBanner] Add support for links to open in a new tab

---

packages/documentation/src/pages/forms/about-the-schema-and-uischema-objects.mdx

After adding the `'ui:reviewField'` documentation, the fix from the review page [a11y fix](https://github.com/department-of-veterans-affairs/vets-website/pull/11118) did not move the `<dl class="review-form">` inside the field element as I anticipated in the original fix.
The field now *must* return a `<div class="review-form">` wrapper containing both `<dt>` and `<dd>` elements as immediate children in order to maintain the accessibility standard.
The above comment and updated code example was added to the documentation  
Original ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/1943
Fix: https://github.com/department-of-veterans-affairs/vets-website/pull/11120
Previous doc addition: https://github.com/department-of-veterans-affairs/veteran-facing-services-tool …

Update 'ui:reviewField' documentation

---

packages/formation-react/package.json
packages/formation-react/src/components/SortableTable/SortableTable.jsx
packages/formation-react/src/components/SortableTable/SortableTable.mdx

**WARNING: THIS PR INCLUDES [THIS PR](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/190).**
**Original Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/3701
This PR adds a new prop called `renderCustomCell` for the `<SortableTable />` component, which is a function that receives the row item as an argument and returns back custom JSX to render within the table cell.
Unit tests.
N/A

Kelsonic 3725 update sortabletable

---

packages/formation-react/package.json
packages/formation-react/src/components/modal/Modal.jsx

bradl3yC 4560 Reset state and wait for teardown complete

---

packages/formation-react/package.json
packages/formation-react/src/components/PromoBanner/PromoBanner.jsx
packages/formation/package.json
packages/formation/sass/modules/_m-promo-banner.scss

Because of the work being done in https://github.com/department-of-veterans-affairs/va.gov-team/issues/4700, we need the Promo Banner component to accept a long string of text. Currently, the long text will fall below the icon.
This changes the HTML, so we'll have to update the sample HTML in the docs too, https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/master/src/_components/promo-banners.md.
Locally messed with component on different viewports
(no effect)

[PromoBanner] Add support for long text

---

packages/documentation/gatsby-config.js
packages/documentation/src/pages/getting-started/common-tasks/previewing-changes.md
packages/documentation/src/pages/getting-started/common-tasks/updating-formation.mdx

I noticed that the link from the Updating Formation page to the Previewing Changes page was broken. Also the Previewing Changes document was out of date and not as clear as it could have been.
Local (note: running the doc site locally is painful because every time you have to rebuild the site it redownloads the entire va.gov-team repo (many gigs) as part of its build process)

Update formation-react docs

---

packages/formation-react/package.json
packages/formation-react/src/components/SortableTable/SortableTable.jsx

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/4558
**Current Behavior:** There's an a tag for header cells.
**Desired Behavior:** The header cells should be buttons.
This PR implements the above behavior.
N/A

Swap a tag to button tag

---

packages/formation-react/package.json
packages/formation-react/src/components/Breadcrumbs/Breadcrumbs.jsx
packages/formation-react/src/components/Breadcrumbs/Breadcrumbs.mdx
packages/formation-react/src/components/Breadcrumbs/Breadcrumbs.unit.spec.jsx
packages/formation-react/src/components/Pagination/Pagination.jsx
packages/formation-react/src/components/Pagination/Pagination.mdx

This PR deprecates the prop `customClasses` for the `<Breadcrumbs />` component. It also adds support for a new prop called `className` to replace `customClasses`. It also updates its documentation with the new prop.
[This is the only place in `vets-website` where this prop is currently used](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/vaos/components/Breadcrumbs.jsx#L7). I will send a follow-up PR with the version bump to update this loc 🙂 
This PR now also adds support for a `className` prop for the `<Pagination />` component. It also updates its documentation with the new prop.

Add/modify props for <Breadcrumbs /> and <Pagination />

---

packages/documentation/src/pages/platform/architecture/cms.mdx

I added a section to the `cms.mdx` page for how to access our CMS accessibility tester added by Nick with this PR: https://github.com/department-of-veterans-affairs/vets-website/pull/10836
* Started the page on `localhost` and ensured the content rendered properly

Adding documentation for CMS a11y checks on preview.

---

packages/formation/package.json
packages/formation/sass/modules/_m-alert.scss

bradl3yC - 5553 - Add styles to enforce padding on firefox

---

babel.config.js
packages/formation-react/package.json

When we reconfigured how Babel worked in this repo, we missed bringing over the lodash Babel plugin.
Local testing
Before and after on VAOS:

Add lodash babel plugin

---

packages/formation-react/src/components/modal/Modal.jsx

Just adding a comment for future maintainers to let them know how the `modal-open` class is used in a potentially unexpected way.
More info https://github.com/department-of-veterans-affairs/vets-website/pull/11712/files#r380869229

Add comment re:usage of `body.modal-open` class

---

lerna.json
packages/formation-react/src/components/SortableTable/SortableTable.unit.spec.jsx

https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/4217
Before solving what I believe to be the root problem, I had to solve two other problems. 
1. There was a bad glob used in the `packages` array in the `lerna.json` config file.
2. There was a unit test that was failing because a component was changed to render a `<button>` instead of an `<a>`. 
[`Lerna`](https://github.com/lerna/lerna) repos typically have a root `package.json` and a `packages` folder. 
- [What does a Lerna repo look like?](https://github.com/lerna/lerna#what-does-a-lerna-repo-look-like)
The [`lerna` config file](https://github.com/lerna/lerna#lernajson) should have a `packages` key with a value that is an array of globs to use as package locations.
In …

Update package globs, and fix failing unit test

---

packages/documentation/README.md

I never remember where to go to find the documentation site. Thought this might be useful.

Add a link to the documentation site

---

packages/documentation/gatsby-config.js

Chris V. asked about if we could link to specific sections of a Gatsby page. There is an [existing Gatsby plugin](https://www.gatsbyjs.org/packages/gatsby-remark-autolink-headers/) to add that functionality. I'd like to test out that plug-in, but the formatting in the `gatsby-config.js` file was inconsistent with prettier's settings. This PR simply applies formatting from prettier so future changes to this file are easier to review. 
We have a [prettier config file in one of the other packages in this repo](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/vagov-eslint/.prettierrc), but not in the root. 
Do we have a standard prettier config that we want to use in some/most/all of our applications? If so, which one is the source of truth? …

Apply formatting from prettier to gatsby-config.js

---

packages/documentation/src/pages/forms/about-the-schema-and-uischema-objects.mdx
packages/documentation/src/pages/forms/available-features-and-usage-guidelines.mdx

Add docs for `hideEmptyValueInReview` uiSchema option
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/11908
N/A
N/A

Add hideEmptyValueInReview docs

---

packages/documentation/src/pages/getting-started/internal-tools.mdx

I replaced this broken link:  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/onboarding/request-access-to-tools.md
with this link: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/request-access-to-tools.md

Updated broken link to va.gov-team repo

---

packages/documentation/src/pages/getting-started/common-tasks/updating-formation.mdx

There was a dead link in the documentation to preview updates to formation-react. Now, that link should point to the correct place.
I did not know how to test the correctness of this change, but my fix follows a pattern used elsewhere in the docs.

Update link to preview formation

---

packages/formation-react/package.json
packages/formation-react/src/components/AlertBox/AlertBox.jsx

When passed both `showOnScroll` and `isVisible`, we need the Alert box to come into view. When statically passing either of those props to the component, we need to run the scroll in `componentDidMount` rather than in `componentDidUpdate`.
The solution works locally.

Add scrollToAlert to componentDidMount in AlertBox

---

packages/formation-react/package.json
packages/formation-react/src/components/Pagination/Pagination.jsx

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199
This PR adds Google Analytics event tracking to Pagination, as per [this analytics request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199#issuecomment-620154353).
I've built it in a way where you would have to __opt-out__ of sending GA events (assuming `window.dataLayer` even exists). Let me know if you think we should change this to where you would have to __opt-in__ to analytics, but it sounded like the Analytics team would like it to be applied to every `<Pagination />` component we're using on va.gov.
Tests pass 🎉 
N/A
<table>
<tr>
<th>Description</th><th>Screenshot</th><th>Datalayer</th>
</tr>
<tr>
<td>
Click on <em>Next</em> link in pagination control </td>
<td>  <img …

Add disableGATracking prop and track w/GA pagination clicks onPageSelect

---

packages/formation-react/package.json
packages/formation-react/src/components/Pagination/Pagination.jsx

**Related comment:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199#issuecomment-622573787
This PR fixes the last event:
Description | Event + dataLayer
--- | ---
Initial Yellow Ribbon search on page | ![image](https://user-images.githubusercontent.com/62304138/80842311-41ffdd80-8bcf-11ea-90e6-8bda4066710d.png)
URL Query Param Preset with options | (none, as expected)
Paginate Next click | ![image](https://user-images.githubusercontent.com/62304138/80842389-6eb3f500-8bcf-11ea-8a80-3192b0981813.png)
Paginate Previous click | ![image](https://user-images.githubusercontent.com/62304138/80842435-8d19f080-8bcf-11ea-9a20-817abaef333c.png)
Paginate Number click | (missing.  Expected `nav-paginate-number` event)

Fix nav-paginate-number event when clicking a pagination number link

---

packages/documentation/src/pages/platform/tools/feature-toggles.mdx

https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/8502
Do you think these changes answer Jesse's questions? Also, does it make sense to include where FEATURE_FLAG_NAMES is imported from in question 8? Thanks!

Kristinagore 8502

---

packages/formation/sass/base/_va.scss
packages/formation/sass/utilities/_visibility.scss

There are two separate screen-reader only definitions:
- `sr-only` - https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/dec6697459836ee2ae88b10c7eaa91b142d8dea6/packages/formation/sass/base/_va.scss#L50-L54
- `vads-u-visibility--screen-reader` - https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/6bc6d59ae3fb119ac3ec1bb27995cd973301a70d/packages/formation/sass/utilities/_visibility.scss#L9-L19
Both need to be updated & match each other.
Per suggestion from an accessibility consultant, the definitions have been [updated to include extra definitions from this resource](https://make.wordpress.org/accessibility/handbook/markup/the-css-class-screen-reader-text/#the-css)
```css
.screen-reader-text {
border: 0;
clip: rect(1px, …
```

Update screenreader only definitions

---

packages/documentation/src/pages/getting-started/internal-tools.mdx

Update Internal tools SOCKS documentation. Added alias to devops sock shell script.
N/A

Add SOCK script docs

---

packages/formation/package.json
packages/formation/sass/modules/_va-pagination.scss

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/8790
Current:
Desired:
N/A
[Find Forms](https://www.va.gov/find-forms):
[Yellow Ribbon](https://staging.va.gov/education/yellow-ribbon-participating-schools/?name=university):

Add overflow visible to pagination for focus styling

---

packages/formation-react/src/components/Telephone/Telephone.jsx
packages/formation-react/src/components/Telephone/Telephone.mdx
packages/formation-react/src/components/Telephone/Telephone.unit.spec.jsx

This PR adds a `<Telephone />` component that builds an accessible telephone link.
To use it, import the component, then pass either a 10 (or 11) digit number in the `tel` property, or pass a "known" number tag in the `use` property.
```jsx
import Telephone, { CONTACTS, PATTERNS } from 'platform/forms-system/src/js/components/Telephone';
export default HotLineLink = () => (
<Telephone contact={CONTACTS.VA_BENEFITS} />
);
```
renders:
```html
<a href="tel:+18008271000" aria-label="8 0 0. 8 2 7. 1 0 0 0." class="no-wrap">
800-827-1000
</a>
```
<details><summary>Another example</summary>
```jsx
<Telephone contact={CONTACTS.GI_BILL}>
1-888-GI-BILL-1
</Telephone>
```
renders:
```html
<a href="tel:+18884424551" aria-label="8 8 8. 4 4 2. 4 5 5 1.">
1-888-GI-BILL-1
</a>
```
</details> …

Add centralized Telephone component

---

packages/documentation/src/pages/getting-started/common-tasks/new-application.mdx

After updating the `generator-vets-website` repo, I'm updating the documentation to reflect those changes

Fix the use of platform alias 

---

packages/documentation/src/pages/getting-started/common-tasks/new-unit-test.mdx

- import react in sample unit test because 'React' must be in scope when using JSX (eslintreact/react-in-jsx-scope)
- rename `componentUnderTest` variable to match enzyme docs

update react unit test sample

---

packages/documentation/gatsby-config.js

Configure syntax highlighting for Github Flavored Markdown using https://www.gatsbyjs.org/packages/gatsby-transformer-remark/

enable GFM for markdown files

---

packages/documentation/src/pages/getting-started/index.mdx
packages/documentation/src/pages/getting-started/workflow/review.mdx
packages/documentation/src/pages/platform/tools/generator.mdx

Makes a number of documentation updates to a couple key "getting started" pages --- content, formatting, and small pain points discovered while trying to run through creating and running an application from scratch.
Getting started page:
* Indents text and samples to be aligned with the ordered bullets
* Adds missing `cd vets-website` between checking out repos and `yarn install`
* Minor wording tweaks in a few places
* Removes unnecessary section descriptions at the top of the doc
* Formatting tweaks in accordance with upcoming developer content style guide
* Adds message about website depending on local backend by default 
Yeoman generator doc:
* Puts all example values in backticks
* Removes example values from headings
* Makes root URL guidance more consistent (examples + text …

Documentation updates for "getting started" flow

---

packages/formation-react/README.md

Formation react readme didn't include the new Telephone.js component
N/A
N/A

Add Telephone to formation-react readme

---

packages/formation-react/package.json
packages/formation-react/src/components/modal/Modal.jsx
packages/formation-react/src/components/modal/Modal.unit.spec.jsx

This PR is a small change to allow consumers of the `Modal` component to customize where programmatic focus starts when the modal is first opened. The primary use case of this feature - or at least, the use case I wanted to solve - is to initiate keyboard focus on the modal content rather than the close button without removing the close button. This is a minor improvement for keyboard users. 
Feedback on how useful this change is would be welcome - it's certainly a corner case but seems like an improvement, in my opinion.
* Manually tested with the [crisis line modal](https://github.com/department-of-veterans-affairs/developer-portal/blob/master/src/components/crisisLine/VeteransCrisisLine.tsx) in the Lighthouse developer portal
* Added unit tests for programmatic focus
Focus on modal …

Add initialFocusSelector prop to Modal 

---

packages/documentation/src/pages/getting-started/index.mdx

This seems to be breaking indentation in the getting started docs.

Removes extra line break in getting-started doc

---

packages/formation-react/package.json
packages/formation-react/src/components/AdditionalInfo/AdditionalInfo.jsx

Fixes department-of-veterans-affairs/va.gov-team#8856.
- Local testing with Safari VoiceOver navigation.
- Added class in dev tools and tested on Staging.

Made AdditionalInfo trigger a block element to fix screenreader focus issue.

---

packages/documentation/src/components/pageFooter/Documentation.jsx
packages/documentation/src/components/pageFooter/PageFooter.jsx

Client Application Documentation site adds an extra path (`/veteran-facing-services-tools`) to the relative path of the site:
`https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started`
This causes that the github links won't work as expected in the local environment. This PR will fix that problem.
Locally

Fix Doc Github link

---

packages/documentation/src/pages/platform/tools/feature-toggles.mdx

This was removed awhile ago in `va.gov-team`, but I think it happened simultaneously with this doc being rewritten by the Content team and got accidentally(?) restored here.
Side note: do we want to rename `featureFlags` and similar across the codebase to stick consistently to the "Toggles" nomenclature?

Removes "feature flags/flippers" nomenclature

---

packages/documentation/package.json
packages/documentation/yarn.lock

The [gatsby-remark-mermaid](https://github.com/remcohaszing/gatsby-remark-mermaid) plugin has `puppeteer` listed as a peer dependency. This PR updates the `puppeteer` version to match the one outlined by the [plugin](https://github.com/remcohaszing/gatsby-remark-mermaid/blob/6005ef28c5bc81501513c9c9b27be641b0858f27/package.json#L32).
Locally tested in the terminal.

Downgrade puppeteer to 2.0.0

---

packages/documentation/src/pages/getting-started/common-tasks/new-end-to-end-test.mdx

The current page for writing new E2E tests is written with Nightwatch in mind.
This updates it to recommend using Cypress with a link to the migration guide.
Locally verified content changes.

Updated end-to-end page with info on Cypress.

---

packages/documentation/src/pages/platform/site-structure/environments.mdx

Update the [old](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Administrative/Accessing-Staging.md) `Accessing Staging` link to the new [one](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/accessing-staging.md) on https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/site-structure/environments.

Update url for accessing staging

---

packages/formation-react/package.json
packages/formation-react/src/components/EmergencyBanner/EmergencyBanner.jsx
packages/formation-react/src/components/EmergencyBanner/EmergencyBanner.mdx
packages/formation-react/src/components/MaintenanceBanner/MaintenanceBanner.jsx

This PR updates the docs for EmergencyBanner and MaintenanceBanner by adding descriptions to props and fixing a rendering bug for EmergencyBanner on the [docs site](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/emergencybanner/).
N/A
N/A

Update docs for EmergencyBanner and MaintenanceBanner

---

packages/documentation/src/pages/getting-started/common-tasks/new-end-to-end-test.mdx

Cypress documentation link now goes to the master branch version rather than a specific version.
Tested that the link goes to the right place.

Updated Cypress link to point to master for consistency.

---

packages/documentation/src/pages/getting-started/common-tasks/new-end-to-end-test.mdx

Needed to update the link yet again after moving the Cypress Migration Guide to the appropriate folder on `va.gov-team`.
Tested that the link works.

Updated link to Cypress Migration Guide.

---

packages/documentation/src/pages/forms/save-in-progress-menu.mdx

The Benefits Delivery at Discharge (BDD) folder has been merged into form 526 all-claims, and thus the test data has moved. This PR updates the url pointing to the `maximal-test.json` for BDD
Related ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/11190
N/A
N/A

Update BDD data link

---

packages/documentation/src/pages/getting-started/common-tasks/new-end-to-end-test.mdx

I moved the Cypress migration guide location in the va.gov-team repo and have updated the link to it from this page.

update link of cypress migration guide

---

packages/documentation/src/pages/platform/tools/feature-toggles.mdx

The feature toggle names should map directly to the toggle names in `features.yml` to avoid any case inflection missteps.
@mr0sari0 discovered the hard way that numbers in the feature toggle names behave a bit unexpectedly. Specifically, if we had `feature_01_name` in `features.yml` in the API and `feature01Name` in `featureFlagNames.js` in `vets-website`, the feature toggle request would send `?features=feature01Name` which the API would translate to `feature01_name`. This, obviously, doesn't match the _actual_ feature toggle name of `feature_01_name`, so the value would always be false.
To avoid this, we can simply send the toggle names in the exact case as they're found in the API, but still use camelCase as the property name for use in JavaScript.

Update feature toggles documentation

---

packages/formation-react/package.json
packages/formation-react/src/components/Telephone/Telephone.jsx
packages/formation-react/src/components/Telephone/Telephone.unit.spec.jsx

In Profile 2.0, we need to render a user's phone number with the same formatting as our current `Telephone` component. However, the phone number is the user's OWN phone number, therefore it needs to not be clickable.
Instead of using css to disable the onClick of the `a` tag (which possibly could lead to a11y issues), this PR adds an optional `notClickable` prop that instead of an `a` tag renders a `span`.
I believe it's a good idea to use the `Telephone` component for this use case, albeit modified, to ensure consistency across formatting and `aria-labels`.
Tested locally, works as expected. Updated unit tests.

Add notClickable prop to Telephone component

---

package.json
packages/documentation/package.json
yarn.lock

The [original PR to install `gatsby-plugin-google-tagmanager` in the Gatsby app](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/374) assumed the VFS Tools repo was a conventional JS repo. However, since the VFS Tools repo is a Lerna repo, the dependencies are handled unconventionally.

Update dependencies to install gatsby-plugin-google-tagmanager in Gatsby app

---

Dockerfile

The documentation site depends on `gatsby-remark-mermaid`, which has a peer dependency on `puppeteer`.
For reasons I don't know right now, it started failing with this error:
```
[2020-09-01T16:08:55.763Z]   Error: Failed to launch the browser process!
[2020-09-01T16:08:55.763Z]   /home/jenkins/workspace/ervices-tools_edit-link-refactor/packages/documentation/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
[2020-09-01T16:08:55.763Z]   TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
```
According to various answers I've found ([such as this](
https://askubuntu.com/questions/547151/error-while-loading-shared-librarie …

Install system dependencies for Puppeteer to fix documentation build.

---

packages/formation-react/src/components/SearchMenu/SearchMenu.jsx

You can observe a breakage when you go to the [SearchMenu page on the documentation site](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/searchmenu/).
This stems from how the `ref` is used. The error is obscured in prod, but in a local build, you would see this error:
> Element ref was specified as a string (myRefName) but no owner was set.
I'm not entirely sure why, but this change addresses the issue as well as updates the component to follow the [newer, non-deprecated approach for using refs](https://reactjs.org/docs/refs-and-the-dom.html#adding-a-ref-to-a-dom-element).
Verified locally that the page now loads properly.

Refactored usage of ref on SearchMenu to fix its documentation page.

---

packages/formation-react/package.json
packages/formation-react/src/components/Telephone/Telephone.jsx
packages/formation-react/src/components/Telephone/Telephone.mdx
packages/formation-react/src/components/Telephone/Telephone.unit.spec.jsx

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/11781
This PR fixes the `<Telephone />` component when a pattern prop is not provided for a 3-digit phone number (e.g. 911 or 711). It also **deprecates `PATTERNS['911']` in favor of `PATTERNS['3_DIGIT']`.
This PR will require a follow-up PR in vets-website to match the version bump but also to **update all use of `PATTERNS['911']` in favor of `PATTERNS['3_DIGIT']` across `vets-website`**.
Tested locally extensively when `<Telephone />` has no props passed and when it only has a 3-digit phone number passed for the `contact` prop (e.g. no `pattern` prop).
N/A

Kelsonic 11781 telephone error

---

packages/formation-react/package.json
packages/formation-react/src/components/Telephone/Telephone.jsx

When using the `<Telephone/>` and updating phone numbers I noticed that the `8554888440` was not in the lookup table so I went ahead and added it for others.

Add HEC phone number

---

packages/documentation/src/pages/forms/about-the-schema-and-uischema-objects.mdx
packages/documentation/src/pages/forms/available-features-and-usage-guidelines.mdx

Add documentation for the `ui:objectViewField` setting
Related: https://github.com/department-of-veterans-affairs/vets-website/pull/14091
N/A
N/A

Add ui:objectViewField docs

---

packages/formation-react/src/components/OMBInfo/OMBInfo.jsx
packages/formation-react/src/components/OMBInfo/OMBInfo.mdx
packages/formation-react/src/components/OMBInfo/OMBInfo.unit.spec.jsx

To increase flexibility, this updates the OMBInfo component to only show the `resBurden` if it a truthy value. My team's UI currently does not have a `resBurden` and in order to not duplicate code,  functionality, and ownership. This feature will allow greater flexibility 
- added unit tests
- Where do I need to update the docs?

added optional resBurden to OMBInfo

---

packages/formation-react/package.json
packages/formation-react/src/components/AlertBox/AlertBox.jsx
packages/formation-react/src/components/AlertBox/AlertBox.mdx

I like constants 🤷 
It's always felt wrong to me to do something like:
```
<AlertBox status="info">
```
With this change we can do:
```
<AlertBox status={ALERT_TYPE.INFO}>
```
Why? Better code completion from editors and/or earlier error/typo detection. It's not TypeScript, but it's better than throwing strings around.

Add ALERT_TYPE enum for use with AlertBox `status` prop

---

packages/formation-react/package.json

Published 5.6.0 incorrectly. Need to bump the version to publish the correct components to NPM.

bump version so we can republish

---

.github/CODEOWNERS

Like it says on the tin. The notable part is that this adds only the front end engineers on the design system team, which is a sub-team of the @department-of-veterans-affairs/vsp-design-system-team.

Add the design system team to CODEOWNERS

---

packages/documentation/src/pages/platform/tools/feature-toggles.mdx

Clarification on how to apply staged rollouts (A/B testing) in Flipper to unauthenticated scenarios. This explicitly ties the Flipper UI options back to the earlier advice on when to "choose cookie_id as the actor_type". If you don't realize that setting has an impact here, then this parts reads as if it only can be applied to logged-in users. The term "Percentage of Logged in Users" can be confusing when the actor_type is set to 'cookie_id' rather than the usual 'user.'
I've also updated the terminology to match the term "staged rollouts" and linked it back to the release plan template.
For further context, this is the Slack thread:
https://dsva.slack.com/archives/CBU0KDSB1/p1601326204185500

'Percentage of Logged in Users' for unauthenticated scenario

---

packages/formation/package.json
packages/formation/sass/base/_va.scss

Download links, based on the [recommended markup](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/152#issuecomment-553127340), includes an `abbr` which doesn't get properly styled when the link has been visited
This PR adds the `abbr` styling for visited links only. Active links only modify the background and hovered links use `inherit` color.
Related: https://github.com/department-of-veterans-affairs/va.gov-team/issues/14258
None
See description

Style nested abbr in visited links

---

babel.config.js
package.json
yarn.lock

This should let us use the `?.` operator for optional chaining in this repo.
https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/452#issuecomment-704638947
Local builds
The result of a failed build in `master` where optional chaining is used but not enabled:
On this PR branch, the build succeeds with the same optional chaining operator used.

Add optional chaining plugin to babel config

---

packages/formation-react/package.json
packages/formation-react/src/components/AlertBox/AlertBox.jsx

We also need to scroll to an AlertBox when `scrollOnShow` is passed and the AlertBox is already (partially) in the viewport). Initially, the scroll logic would not run when the AlertBox was only a few pixels in the viewport which was confusing for the user.
I needed to use a `setTimeout` to ensure the `ref` in the scroll logic was defined, since putting any logic in `componentDidMount` does not guarantee that it's actually already painted to the DOM.
Works locally.

Fix alert box scroll when scrollOnShow is true

---

packages/formation-react/package.json
packages/formation-react/src/components/AlertBox/AlertBox.jsx

This is a follow up to [this PR](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/452/commits/cd7df9f3d5ce8750c82d9a610ae06ae318edc6de).
This PR fixes the error thrown in vets-website after upgrading formation-react to 5.7.0.

Fix undefined ref issue

---

packages/formation-react/package.json
packages/formation-react/src/components/Telephone/Telephone.jsx
packages/formation-react/src/components/Telephone/Telephone.mdx

Adds U.S. Department of the Treasury (Debt Management Services) phone number to contact list

Add Treasury DMS phone number to contact list

---

packages/formation-react/src/components/AdditionalInfo/AdditionalInfo.stories.jsx

Created story for `AdditionalInfo` component | Closes [#15403](https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/15403)

15403: Storybook Component - AdditionalInfo

---

packages/formation-react/src/components/ErrorableCheckboxGroup/ErrorableCheckboxGroup.stories.jsx

Created story for ErrorableCheckboxGroup component | closes [#15409](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15409)

15409: Storybook Component - ErrorableCheckboxGroup

---

packages/formation-react/package.json
packages/formation-react/src/components/Telephone/Telephone.jsx
packages/formation-react/src/components/Telephone/Telephone.mdx
packages/formation-react/src/components/Telephone/Telephone.unit.spec.jsx

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/14609
This PR bumps formation-react for the update in the `<Telephone />` component and updates all VA311 numbers. If I missed any, please lmk asap!! 🙂 
N/A
N/A

Update va311 number

---

packages/formation/package.json

This is related to #492. It added the responsive `<Table>` component to `formation-react` along with some css to `formation`, but the `formation` package wasn't updated for publishing. This updates the version number of `formation`.

Bump formation version for Table css changes

---

packages/documentation/src/pages/visual-design/index.mdx

Just fixed a small typo on the visual design page.

Fixed small typo on the Visual Design documentation page

---

packages/formation-react/src/components/Table/Table.stories.jsx
packages/formation/package.json
packages/formation/sass/modules/_m-responsive-tables.scss

Related to #492 
This turns the `<Table>` component into a "list table" on smaller screens by:
- removing the table headers at the top
- allowing the `<td>` elements to be displayed with `flex` so that they stack
- Also setting `flex-wrap: wrap` so that longer content can fit below the column label
It also improves the stories for `<Table>` by adding better data, and adding a new story to show how to pass in a piece of JSX instead of a string for a row's data.

Change table css on small screens

---

packages/formation-react/package.json
packages/formation-react/src/components/Table/Table.jsx
packages/formation/package.json
packages/formation/sass/modules/_m-responsive-tables.scss

After some conversation in slack [it was decided](https://dsva.slack.com/archives/C52CL1PKQ/p1604527710459700?thread_ts=1604524377.447400&cid=C52CL1PKQ) to remove the colon from the column label on mobile views, and also to force all content to appear underneath the label.

Table tweaks

---

package.json
packages/formation-react/package.json
yarn.lock

The `react-scroll` dependency is declared in the root `package.json`, but only ever used in `formation-react`. This lack of a dependency causes problems for us when we try to deploy storybook from https://github.com/department-of-veterans-affairs/component-library
This change will declare the dependency in the child package (formation-react), so that when we update the mirrored repo, the storybook deploy shouldn't run into any problems.

Move react-scroll to formation-react

---

packages/documentation/src/pages/platform/tools/downtime-notifications.mdx

Add some information about how to add a Downtime Notification for a new, or unlisted, backend service.

Add backend documentation for Downtime Notifications

---

packages/formation-react/.storybook/preview-body.html
packages/formation-react/src/Introduction.stories.mdx

Adds the intro page to storybook with a beta banner on all stories.
Banner shows up on `Docs` pages too.

Add the intro and beta banner to storybook

---

package.json
packages/formation-react/src/components/Table/Table.jsx
packages/formation-react/src/components/Table/Table.stories.jsx

[Original Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15484)
Often times numerical data is supposed to be right aligned in tables and in fact, our design system calls for right aligning numerical data in tables as well as material design and AP style guides call for right aligning numerical data in tables as well. This PR adds a prop to the `<Table />` component to allow a key of `rightAlign` to be passed in with he value true on a field and have that field get the standard design system right align class added to right-align it.
The class that is added is from medium screens and up since on mobile the table stacks and we don't want the data right aligned then.
All existing unit tests pass, further unit tests are coming in future iterations

Added logic to allow for right aligning

---

packages/vagov-eslint/.prettierrc

The auto-formatting on file save was adding parens around single-argument arrow functions. We experienced this behavior in Emacs, Vim, and VS Code, so it's not an editor-specific configuration. I have no idea why it was doing this...and then why eslint was saying it was an error according to the prettier/prettier rule, but hey. This fixes it. :see_no_evil:
For some context, when I ran `npx eslint --fix <file>` on the file with unwanted parens, it removed them. As did `npx prettier --write <file>`. So this is very confusing to me.
Tested the behavior locally.
N/A

Stop auto-formatting with linting errors

---

packages/formation-react/src/components/ErrorableMonthYear/ErrorableMonthYear.jsx
packages/formation-react/src/components/ErrorableMonthYear/ErrorableMonthYear.stories.jsx

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/15412
While creating the story, I removed the `row` class from the component because there was a misalignment between the label and the inputs.
Visual testing in Storybook.
*Default*
*Error message*
Note: The error doesn't show up well, but fixing it is out of the scope of this PR.
*Required*

ErrorableMonthYear story

---

packages/formation-react/src/components/ErrorableTextArea/ErrorableTextArea.jsx
packages/formation-react/src/components/ErrorableTextArea/ErrorableTextArea.stories.jsx

Add some stories for `<ErrorableTextArea />`

Errorable text area story

---

packages/formation-react/src/components/ErrorableTextInput/ErrorableTextInput.jsx
packages/formation-react/src/components/ErrorableTextInput/ErrorableTextInput.stories.jsx

Adds some stories for `<ErrorableTextInput />`

Errorable text input story

---

packages/formation-react/src/components/ErrorableSelect/ErrorableSelect.jsx
packages/formation-react/src/components/ErrorableSelect/ErrorableSelect.stories.jsx

Some stories for `<ErrorableSelect />`
This also removes the `selectClass` prop from the component which wasn't used anywhere. `additionalClass` can be used instead.

Errorable select story

---

packages/formation-react/src/components/IconBase/IconBase.stories.jsx

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/15420
Like I state in the story, it doesn't actually _do_ anything. I'm strongly considering deleting it entirely since it's just a straight-up pass-through for `<svg>`.
:man_shrugging:

IconBase stories

---

packages/formation-react/src/components/Table/Table.stories.jsx

Removes an unnecessary prop from the `<Table>` component's storybook template.
This is so the demo will be clearer.
---
The optional chaining here means that we don't need to pass `currentSort` in:
https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/50d298a11261d270559fcca7c7a1544de29de4e5/packages/formation-react/src/components/Table/Table.jsx#L28-L36
Storybook

Remove currentSort prop from defaultArgs

---

packages/formation-react/src/components/PromoBanner/PromoBanner.jsx
packages/formation-react/src/components/PromoBanner/PromoBanner.stories.jsx

Add some stories for `<PromoBanner>`.
Fun fact - the `<PromoBanner>` is styled so that it is fixed to the bottom of the page, so this creates some interesting results on the Storybook docs page.
**Note**: At the moment, this component isn't _actually_ used in `vets-website`.

PromoBanner stories

---

packages/formation-react/src/components/SortableTable/SortableTable.jsx
packages/formation-react/src/components/SortableTable/SortableTable.stories.jsx

Adds some stories for `<SortableTable>`, basically copied from the `<Table>` stories.
This component shouldn't exist, and it is only used once in `vets-website` where it is configured so that it doesn't sort. Replacing that use with `<Table>` would be good, but might not be a high priority.

Sortable table stories

---

package.json
packages/formation-react/package.json
packages/formation/package.json
scripts/prepublish.js
yarn.lock

Like it says on the tin, this PR adds a `prepublishOnly` script to check if the branch is `master` to prevent publishing from non-master branches (which has happened a few times now).
See screenshots.
Test that the prepublish script exits with a status code 1 for non-master branches, but status code 0 on `master`.
**Note:** I updated the script name to `prepublish.js` after taking this screenshot.
Test that the `prepublishOnly` hook disallows publishing when not on `master`.

Check branch before publishing

---

.circleci/config.yml
packages/formation-react/.storybook/preview.js

We noticed that after #546 was merged, CircleCI was failing to build storybook due to some issues with trying to load things from `formation`.
https://app.circleci.com/pipelines/github/department-of-veterans-affairs/veteran-facing-services-tools/94/workflows/08264a3e-e36d-4e48-9246-150c739f4e82/jobs/132
The problem was that we have a repo-level `package.json` with some of the dependencies, and then in `packages/formation-react` we have another `package.json` with some more dependencies. These weren't being installed, which means storybook didn't have access to formation.
https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/93827b0c15be749c7180525759a06d44df447820/packages/formation-react/package.json#L45
This PR makes sure that the `formation-react` …

Fix the storybook build in Circle

---

packages/documentation/src/pages/getting-started/common-tasks/new-end-to-end-test.mdx

Resolves https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/16476
Feature updates E2E testing documentation to point to single source of truth for Cypress test documentation and deprecates prior Nightwatch testing instructions.
- [x ] Changes have been tested in vets-website
- [x ] Changes have been tested in IE11, if applicable
- [x ] Documentation has been updated, if applicable
- [x ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

Update Veteran Facing E2E page for Cypress

---

packages/formation-react/package.json
packages/formation-react/src/components/OMBInfo/OMBInfo.jsx
packages/formation-react/src/components/OMBInfo/OMBInfo.mdx
packages/formation-react/src/components/OMBInfo/OMBInfo.unit.spec.jsx

The OMB number component needs to have a little more flexible to meet requirements
- For forms with no OMB number, those fields should be hidden
- The content in the `Privacy Act Statement` should reflect the form being used. So if there is no res burden, then do not show the res burden section.

Updated OMB to be more dynamic. 

---

scripts/prepublish.js

Turns out `execSync` returns a buffer, which makes total sense. This buffer contained a newline character, which explained the dumb thing I was doing in the `console.log()`.
The latest `master` needed publishing, so I made the change there and tested by publishing. On this branch, I added a `process.exit(1)` at the end of the pre-publish script for safety and tried publishing again. I got the error I expected (wouldn't let me publish).

Fix the pre-publish script

---

packages/formation-react/package.json
packages/formation-react/scripts/build.js

Telephone.js was invalid because it was importing `./contacts`, but `contacts.js` wasn't being built by our build process because it was a `.js` file and not a `.jsx` file. This fixes that.
Built locally and verified `contacts.js` is built as expected.

Build .js files

---

packages/documentation/src/pages/forms/creating-custom-fields-and-widgets.mdx

This adds some documentation for the custom fields and widget props that can be used

Add documentation for props passed to custom fields and widgets

---

packages/formation-react/package.json
packages/formation-react/src/components/DropDownPanel/DropDownPanel.jsx

Add class name prop to DropDownPanel for styling purposes
N/A
N/A
here is the vets-website PR that is relying on the change:
https://github.com/department-of-veterans-affairs/vets-website/pull/15347
And here is the ticket that is being addressed:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/16965

Add dropdownpanel classnames

---

.circleci/config.yml

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/15169
Now that we are deploying design.va.gov from CircleCI (https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/358), we can go ahead and deploy storybook to production from CircleCI.
**Note**: This does _not_ mean that Storybook is considered launched or finished. When it is officially announced, we will merge these PRs to add links to it in the appropriate places:
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/354
- https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/555
- [CircleCI deploy](https://app.circleci.com/pipelines/github/department-of-veterans-affairs/veteran-facing-services-tools/167/workfl …

Add CircleCI workflow for prod storybook deploy

---

packages/formation-react/src/components/ErrorableCheckbox/ErrorableCheckbox.stories.jsx
packages/formation-react/src/components/ErrorableCheckboxGroup/ErrorableCheckboxGroup.stories.jsx
packages/formation-react/src/components/ErrorableDate/ErrorableDate.stories.jsx
packages/formation-react/src/components/ErrorableFileInput/ErrorableFileInput.stories.jsx
packages/formation-react/src/components/ErrorableMonthYear/ErrorableMonthYear.stories.jsx
packages/formation-react/src/components/ErrorableNumberInput/ErrorableNumberInput.stories.jsx
packages/formation-react/src/components/ErrorableRadioButtons/ErrorableRadioButtons.stories.jsx
packages/formation-react/src/components/ErrorableSelect/ErrorableSelect.stories.jsx
packages/formation-react/src/components/ErrorableTextArea/ErrorableTextArea.stories.jsx
packages/formation-react/src/components/ErrorableTextInput/ErrorableTextInput.stories.jsx

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/18145
Moved the `Errorable*` components out of the `Form controls` directory in Storybook.
**Note:** We're moving all the `Usage` documents in a separate PR, so I left it alone for now to avoid merge conflicts.

Remove Form controls from the Storybook side nav

---

packages/formation-react/.storybook/preview.js

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/18147
This should provide a better user experience for our Storybook users. It sets custom viewports based off of [breakpoints from the design system](https://design.va.gov/design/breakpoints). Additionally, it uses the `medium` viewport as a default, which means that the responsive viewports button gets a label when you first open the page.
By setting a named default, the viewport is ironically no longer responsive (see third screenshot). However, `Reset viewport` can be used to turn the viewport responsive again.
Local storybook

Add custom viewports & set a named default

---

packages/documentation/src/pages/forms/available-features-and-usage-guidelines.mdx
packages/documentation/src/pages/forms/available-widgets.mdx
packages/documentation/src/pages/forms/form-tutorial-advanced.mdx
packages/documentation/src/pages/forms/form-tutorial-basic.mdx
packages/documentation/src/pages/forms/form-tutorial-intermediate.mdx

Add docs for the new `radio` and `yesNo` widget `ui:options`. This change will allow custom widget properties (`widgetProps`) to be included on each input. Specifically this was meant to enable adding `aria-describedby` properties to specific inputs to improve accessibility.
Related:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/316
- https://github.com/department-of-veterans-affairs/vets-website/pull/15586
N/A - doc updates only
N/A

Update docs for custom radio props

---

packages/documentation/src/pages/forms/available-features-and-usage-guidelines.mdx
packages/formation-react/src/components/HelpMenu/HelpMenu.jsx

The old help desk number `855-574-7286` is outdated and needs to be replaced with `800-698-2411`.
Also, changing the TTY number to `711` per the Slack conversation.
Related:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/18345
- https://dsva.slack.com/archives/CBU0KDSB1/p1610393236325800
- https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/438 will fix Telephone docs reference
N/A
N/A

Replace old help desk number

---

packages/formation/js/accordion.js
packages/formation/package.json

This PR adds onto the Formation bundle's accordion JS. If the hash in the document's URL matches an accordion panel's element ID, the accordion panel will automatically expand open on page load. This is so content editors can link to specific accordion panels and have the panel's content automatically revealed.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/15798
I tested against my local vets-website by changing the site-wide import to use my local Formation repo.

Auto-expand accordion panels by URL hash

---

packages/formation/package.json

Somehow there were two merged to bump Formation to 6.11.0 so now we need a 6.12.0
https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/577
https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/576

Bump Formation to 6.12.0

---

packages/documentation/src/pages/getting-started/workflow/deploy.mdx

Confirmed that the builds will not conflict, whichever is clicked first, will deploy first. In the screenshot attached a full build is in progress and you can see in the far left that a partial build is queued up behind it.
Asked Ops, and ran a physical test deploying a content-only build during a scheduled deploy.

Adding note about the Jenkins pipeline and deploy process

---

packages/documentation/src/pages/forms/about-the-schema-and-uischema-objects.mdx

Updating docs to match the use of `H4`s inside the form review & submit accordion content.
Related:
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/368
- https://github.com/department-of-veterans-affairs/vets-website/pull/15717
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/17846
N/A - doc update only
N/A

Update accordion content docs

---

packages/formation/package.json
packages/formation/sass/modules/_m-print.scss

Currently, in print preview, we append `https://va.gov${href}` during print preview, so that the printed page still tells users where the links go. This PR does not debate whether we should really be doing that or not -  it's just fixing some obvious issues. See [Slack discussion](https://dsva.slack.com/archives/C7NJWUA8K/p1611093271006000) with design system council.
The issues this fixes are -
- Prepend the domain onto the HREF if the HREF starts with a leading `/`
- Show the plain HREF if the HREF starts with `http`
https://github.com/department-of-veterans-affairs/va.gov-team/issues/18337
Observed `/coronavirus-veteran-frequently-asked-questions/` using the ["print" render mode](https://stackoverflow.com/questions/9540990/using-chromes-element-inspector-in-print-preview-mode)

[Print view] Prepend website domain only when links start with "/"

---

packages/formation/js/sidenav.js
packages/formation/package.json

This fixes a bug in Safari where focus was not properly managed when opening the mobile side nav.

Fix mobile side nav focus bug

---

packages/documentation/src/pages/forms/config-options.mdx
packages/documentation/src/pages/forms/save-in-progress.mdx
packages/documentation/src/pages/forms/wizard.mdx
packages/documentation/src/sidebar.js

Adding documentation for the two save-in-progress form restart options. These options allow you to add a custom form wizard session storage key & choose a target destination page upon manually restarting a form.
Related:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/13814
- https://github.com/department-of-veterans-affairs/vets-website/pull/15821
N/A - doc update
N/A

Add docs for saveInProgress form restart options

---

packages/documentation/src/scss/_code.scss

The font size on pre element is pretty small, I just updated it.
Before:
After:

bumped up from size on <pre>

---

packages/formation/sass/_shame.scss
packages/formation/sass/modules/_m-form-elements.scss

This PR fixes two issues with the date widget:
- The full month name is now contained within the month select, but the `10rem` width isn't adequate for longer month names. Increased to `12rem`.
- Error states change the width of the form elements in two areas:
- Selects were set to `calc(100% + 1.5rem)` in the formation styling - removed
- USWDS styles sets an error state of the select and input to `calc(100% + 1.9rem)` - overridden by higher-specificity selectors
Related:
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/394
- https://github.com/department-of-veterans-affairs/vets-website/pull/15935#discussion_r570664989
- https://github.com/department-of-veterans-affairs/vets-website/pull/15935#discussion_r573985356
Visual only

Update date widget css

---

packages/formation/package.json
packages/formation/sass/modules/_m-process-list.scss

This PR removed the font-size style rule from headings inside of process lists so that heading hierarchies are distinguishable visually.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/7770
Pointed my local website at the SCSS file being edited. Tested against `/decision-reviews/supplemental-claim/`
Tested against `/decision-reviews/supplemental-claim/`
Since H4s have the same font-size as H3s inside of process lists we have to use `<strong>` tags instead to help distinguish the content them visually.  This looks fine but produces a screen-reader error because the strong tag doesn't carry meaning like a heading does.
We should just remove the font-size declaration from the SCSS for headings inside of process lists. The style w/o that rule still looks good.

[Process List] Remove font-size style rule

---

packages/formation/sass/base/_b-mixins.scss
packages/formation/sass/base/_va.scss
packages/formation/sass/modules/_m-action-link.scss
packages/formation/sass/modules/_m-button.scss

Adds styles for the white action link
https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/22151
Also adds mixin for color transition.
Visual testing using the `feat/22151--white-action-link` branch on [component-library](https://github.com/department-of-veterans-affairs/component-library/pull/71)

Add styles for white action link

---

packages/formation/package.json

Adding a minor version bump for the white action link styles (forgot to bump in original PR)

minor version bump for white action link styles

---

packages/documentation/src/pages/forms/available-features-and-usage-guidelines.mdx
packages/documentation/src/pages/forms/available-widgets.mdx
packages/documentation/src/pages/forms/form-tutorial-advanced.mdx
packages/documentation/src/pages/forms/form-tutorial-basic.mdx
packages/documentation/src/pages/forms/form-tutorial-intermediate.mdx

Add documentation for the `selectedProps` `ui:option` - specific to the `RadioWidget` and `YesNoWidget`
Related:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/19733
- https://github.com/department-of-veterans-affairs/vets-website/pull/16641
N/A
N/A

Add `selectedProps` documentation

---

packages/formation/package.json
packages/formation/sass/modules/_m-form-elements.scss

Closes https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/20546
Manual. Linked to vets-website and checked form to make sure width was enough to account for longer month names.
To test:
Before:
After:

Increase width of month select box

---

packages/formation/package.json
packages/formation/sass/modules/_m-action-link.scss

First part of fixing https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/426
n/a
n/a

rename action link classes

---

packages/formation/package.json
packages/formation/sass/modules/_m-action-link.scss

To align the link vertically, this removes the horizontal padding. Crystabel brought it to my attention in [this Slack thread](https://dsva.slack.com/archives/G01BJ3ESXL4/p1618432757012100).
Note how the darkened background doesn't extend to the sides of the link on hover.

Remove the horizontal padding for action links

---

packages/documentation/src/pages/getting-started/workflow/deploy.mdx

Add a note to the _Creating a Release_ section about  potential overriding releases.

Update creating release documentation

---

packages/documentation/package.json
packages/documentation/yarn.lock

Adding some yarn resolutions for dependencies with high-severity alerts in the documentation package.
ran documentation app locally. Watched for errors in Gatsby build.

upgrade dependencies with high-severity alerts

---

packages/documentation/src/pages/forms/form-tutorial-intermediate.mdx

The docs are showing a validation example using `ui:validation` instead of `ui:validations`.
N/A
N/A

Fix 'ui:validations' name in docs

---

packages/documentation/src/pages/platform/index.mdx

Fixes a small typo: `adn`->`and`

Fix small typo on platform info page

---

packages/documentation/src/pages/platform/architecture/reverse-proxy.mdx

Added documentation on how to deploy the reverse proxy.
Intentionally left out build & deploy instructions as it seems like that is very tied to the operations team.
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/7646

Added revproxy deployment docs

---

packages/formation/js/back-to-top.js

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/22546
**Slack:** https://dsva.slack.com/archives/C52CL1PKQ/p1622128639266400

Update navigateToTop for back to top component

---

packages/documentation/src/components/dashboard/CommitsTable.jsx

The Frontend Support Dashboard is currently broken because we have commits coming through with no author information. This change updates our code to account for that
visual

account for no github login info in support dashboard

---

packages/formation/__tests__/js/back-to-top/back-to-top.test.js
packages/formation/js/back-to-top.js

https://github.com/department-of-veterans-affairs/va.gov-team/issues/25103
I believe this is the result of `window.scrollY` being undefined in IE11: https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY#browser_compatibility
unit testing

Fallback to window.pageYOffset for IE11

---

packages/formation/__tests__/js/back-to-top/back-to-top.test.js
packages/formation/js/back-to-top.js
packages/formation/package.json

https://github.com/department-of-veterans-affairs/va.gov-team/issues/25103
This is a follow up on https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/648 which ensured IE compatibility for the back to top component. The issue still persists and it appears to be a result of an unrelated check for the existence of the footer component before executing the breakpoint check on scroll. Currently we run checks for 2 separate elements before running the code that relies on the existence of either of them. This PR removes the too early check for `footer` and moves that check to where it's needed. See the video for the effect of both lines in this pr on IE11
https://user-images.githubusercontent.com/3144003/128720680-4ddc51fa-95b3-41c5-be64-523fb5e56649.mov
local …

Run breakpointCheck even when footer is not present

---

packages/documentation/src/pages/forms/bypassing-schemaform.mdx
packages/documentation/src/sidebar.js

This PR adds the documentation for https://github.com/department-of-veterans-affairs/vets-website/pull/18096 and https://github.com/department-of-veterans-affairs/vets-website/pull/18196.
Tested that it builds the page and adds it to the sidebar. See the screenshot below.

Add documentation for bypassing the SchemaForm

---

packages/documentation/src/pages/getting-started/common-tasks/new-widget.mdx

Found no instances of this feature being used and no legacy files in the file system. Looks like it was removed and the docs were no updated.
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/9535

Removed static page widget docs as it isn't used anymore

---

packages/documentation/src/pages/getting-started/common-tasks/debugging-tests.mdx
packages/documentation/src/pages/getting-started/common-tasks/test.mdx
packages/documentation/src/scss/_deprecation-message.scss

This PR adds deprecation messages with links to the new location for the unit testing sections of a couple of shared testing documents
The list of documents that need to be deprecated can be found here: https://docs.google.com/spreadsheets/d/1vDQlI_lk9GTQuqw4eMmDe8CAHvNjVmjW3CGRDp0I9iU/edit#gid=1510466462
Checked each link to make sure they direct the user to the correct document

add deprecation messages to unit testing sections

---

packages/formation/package.json
packages/formation/sass/modules/_m-back-to-top.scss

See companion PR in content-build: https://github.com/department-of-veterans-affairs/content-build/pull/505
**The other PR should merge first**
Local
`/decision-reviews/supplemental-claim/` Before:
`/decision-reviews/supplemental-claim/` After: 
`/resources/how-to-get-free-language-assistance-from-va/` Before:
`/resources/how-to-get-free-language-assistance-from-va/` After:

Remove position relative from usa-content in Back to Top component

---

packages/formation/sass/modules/_m-modal.scss

Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/225
Manual testing
Before:
After:

Add margin to Modal body to prevent overlap with Close button

---

packages/formation/package.json
packages/formation/sass/modules/_m-nav-linkslist.scss

https://github.com/department-of-veterans-affairs/va.gov-team/issues/15244
We are adding links with a non breaking space to in-page links to ensure focus moves correctly, so we want to remove `cursor: pointer` from that space.
See this pr in content-build for usage https://github.com/department-of-veterans-affairs/content-build/pull/575
local

Add cursor default to .va-nav-linkslist-link

---

Jenkinsfile
package.json
webpack.config.prod.js
yarn.lock

This PR addresses this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/2259)
Seems to be an issue pertaining to `sass`. See [thread](https://github.com/twbs/bootstrap/issues/34051#issuecomment-845838276). This PR uses the recommendation to resolve issue.
Install was failing due to collision of `close.svg`. As an alternative since the files could potentially differ, webpack will now ensure no collision. See following error resolve:
```
100 assets
13 modules
ERROR in ./sass/full.scss
Module build failed (from ../../node_modules/mini-css-extract-plugin/dist/loader.js):
Error: Conflict: Multiple assets emit different content to the same filename img/close.svg
at Compilation.emitAsset (/Users/oseasmoran/Projects/VA/veteran-facing-services-tools/node_modules/webpack …
```

Fix  install / sass errors

---

packages/formation/package.json
packages/formation/sass/modules/_m-hub-page-link-list.scss

https://github.com/department-of-veterans-affairs/va.gov-team/issues/15244
From [comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15244#issuecomment-929364244)
would it be possible for us to remove the focus halo from the heading? Since it is not an interactive element, previous VA guidance has recommended not to have the focus halo around it even if we send focus to it.
local

Remove focus outline from .hub-page-link-list__title

---

packages/formation/sass/modules/_m-responsive-tables.scss
packages/formation/sass/modules/_va-pagination.scss

Closes <https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/248>
When focus is on the last item in the pagination the `>` is outside of the focus outline, but should be within (the 'Next' link). Example:
The ticket doesn't mention it, but the same is true for the 'Previous' link.
I fixed the issue with both 'Next >' and '< Previous'.

Focused item MUST be contained by focus outline, pagination Next &gt;

---

packages/documentation/src/pages/getting-started/workflow/deploy.mdx
packages/documentation/src/pages/platform/architecture/build-deploy-flows.mdx

[Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28990) associated with
This PR adds the deprecation banner to deploy documentation which has been recently [published](https://depo-platform-documentation.scrollhelp.site/developer-docs/Deployments.1844641889.html) [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/Build-and-deploy-process-flows.1844346924.html)
N/A. Snippet copied from [here](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/046910f8838d1a30fe77a39214370ef0626e83a3/packages/documentation/src/pages/getting-started/workflow/overview.mdx)

Add deprecation message to deploy doc

---

packages/documentation/src/pages/index.jsx

The dashboard links on the documentation homepage aren't working because they aren't prepended with `frontend-support-dashboard`.
Tested locally.

Fix dashboard links

---

packages/documentation/package.json
packages/documentation/yarn.lock

Removes the `gatsby-transformer-javascript-frontmatter` plugin since it isn't being used anymore.
Locally and in CI

Remove gatsby-transformer-javascript-frontmatter

---

packages/documentation/src/pages/frontend-support-dashboard/cross-app-import-report/app.jsx
packages/documentation/src/pages/frontend-support-dashboard/cross-app-import-report/archive/2022-01-24-cross-app-imports.json

The updated cross app import report as of Feb. 7th.  There's an increase in the number of isolated apps. This largely because of a few new apps in `vets-website`.

Update cross app import report 2/7

---

.github/workflows/continuous-integration.yml
Jenkinsfile

This PR reverts https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/759.
It looks like deploy job in GHA doesn't have access to the correct API key.

Deploy from Jenkins again

---

packages/documentation/src/pages/forms/about-the-schema-and-uischema-objects.mdx
packages/documentation/src/pages/forms/available-widgets.mdx
packages/documentation/src/pages/forms/form-tutorial-advanced.mdx

Adding docs for the `ui:autocomplete` enhancement - https://github.com/department-of-veterans-affairs/react-jsonschema-form/pull/14
Ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/37849
N/A
N/A

Add `ui:autocomplete` docs

---

.github/workflows/continuous-integration.yml
Jenkinsfile

Reverts the deploy from happening in GitHub Action. The `Deploy` job needs to be refactored to deploy with a token rather than a password.
[Slack thread](https://dsva.slack.com/archives/GLDNCMRSP/p1646070956873819)

Revert GHA deploy

---

.github/workflows/continuous-integration.yml
Jenkinsfile

This PR updates the `Deploy` job in GitHub Actions to properly use the token for publishing the documentation site to GitHub Pages.
Will test once merged in `master`.

Update GHA deploy job to use token

---

packages/documentation/src/pages/frontend-support-dashboard/cross-app-import-report/app.jsx
packages/documentation/src/pages/frontend-support-dashboard/cross-app-import-report/archive/2022-02-24-cross-app-imports.json

Updates the cross app import report as of 3/2/22. No changes to percentage of apps isolated.
Now that we have the new `vetsgov-website-builds-s3-upload-test` S3 bucket, we can automate this report. I'll add a workflow for uploading to the bucket in `vets-website` and update the report in a seperate PR

Update cross app import report 3/2/22

---

packages/formation/package.json
packages/formation/sass/base/_b-mixins.scss
packages/formation/sass/base/_b-variables.scss
packages/formation/sass/base/_va.scss
packages/formation/sass/modules/_m-form-process.scss
packages/formation/sass/modules/_m-nav-sidebar.scss

Part of https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/654
Companion PR: https://github.com/department-of-veterans-affairs/component-library/pull/433
I left review comments, but links that aren't in the header/footer aren't getting the box-shadow styles because they could wrap, and box-shadow focus styling would look bad. Keeping the outline like we currently have (but with a different color) and setting the color to be dark and the background to be light should ensure that a focused link will have good contrast no matter where it appears.
`yarn link` and tested builds in `vets-website` and `content-build`
<details>
<summary>Example of focus styling for buttons, links, and wrapped links where the ends are far apart</summary>
</details>
<details> …

Update focus styles

---

packages/eslint-plugin/lib/rules/deprecated-classes.js
packages/eslint-plugin/package.json
packages/eslint-plugin/tests/lib/rules/deprecated-classes.js

Fixes crash in deprecated-classes rule conditions

Fix deprecated-classes rule condition checks

---

packages/formation/package.json
packages/formation/sass/base/_b-mixins.scss
packages/formation/sass/base/_b-variables.scss
packages/formation/sass/base/_va.scss
packages/formation/sass/modules/_m-form-process.scss
packages/formation/sass/modules/_m-nav-sidebar.scss

Reverts department-of-veterans-affairs/veteran-facing-services-tools#822
These changes are being reverted so that we can publish a utility class fix and update `formation` in `vets-website` without also introducing the new focus style. https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/838#pullrequestreview-1013892044

Revert "Update focus styles"

---

packages/documentation/package.json
packages/documentation/src/components/dashboard/DashboardDataFetch.jsx
packages/documentation/yarn.lock

This PR adds a function that uses octokit to GET the latest CI workflow runs for a provided repository. The function maps the response to a single object that consists of the commit SHAs as keys and the workflow run status as values.

[41668] Add function for getting CI workflow runs

---

packages/eslint-plugin/index.js
packages/eslint-plugin/lib/config/recommended.js
packages/eslint-plugin/lib/rules/no-cross-app-imports.js
packages/eslint-plugin/package.json

Adding a custom linter rule to warn about cross-app-imports. We can't yet fail the build with this rule because we have too many existing cross-app imports. But we can warn engineers when they add a cross-app import.
See [ticket](https://app.zenhub.com/workspaces/vsp---release-tools-fe-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/41208) for more info.
Local CLI testing:
- Run `yarn link` in `veteran-facing-services-tools/packages/eslint-plugin`
- Run `yarn link @department-of-veterans-affairs/eslint-plugin` in vets-website
- Run `yarn lint` in vets-website
Editor testing:
- Cross-app imports produce linter warnings in VS Code

Add no-cross-app-imports custom rule (#41208)

---

lerna.json
packages/eslint-plugin/package.json
packages/eslint-plugin/tests/lib/rules/axe-e2e-tests.js
packages/eslint-plugin/tests/lib/rules/prefer-web-component-library.js

This PR fixes broken tests for the `eslint-plugin` package by updating the rule path in `axe-e2e-tests.js` and using the new `react-bindings` location in the test for `prefer-web-component-library.js`. Additionally, this PR adds `eslint-plugin` to the lerna config, so tests for the plugin will run in CI. 
Tested locally and in CI.

Fix eslint-plugin tests

---

packages/eslint-plugin/index.js
packages/eslint-plugin/lib/config/recommended.js
packages/eslint-plugin/lib/rules/prefer-telephone-component.js
packages/eslint-plugin/lib/rules/telephone-contact-3-or-10-digits.js
packages/eslint-plugin/package.json
packages/eslint-plugin/tests/lib/rules/prefer-telephone-component.js
packages/eslint-plugin/tests/lib/rules/telephone-contact-3-or-10-digits.js
packages/eslint-plugin/yarn.lock

Part of https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/864
This adds two new custom ESLint rules:
This is an autofixable ESLint rule which will trigger on the pattern `<a href="tel:..."`. When run with `--fix`, it will replace that with `<va-telephone>`. It will also:
- replace the `href` attribute with `contact
- strip all non-digits out of the contact number
- remove child content since the component doesn't allow it
- remove the `aria-label` if present since the component will add its own to the link
This is a rule added as part of this PR to try to prevent the first rule from applying a fix that results in the `<va-telephone>` component having a bad `contact` prop, i.e. one that doesn't have 3 or 10 digits. It might flag on code that results …

Add ESLint rules for telephone numbers

---

packages/eslint-plugin/lib/rules/prefer-web-component-library.js
packages/eslint-plugin/package.json
packages/eslint-plugin/tests/lib/rules/prefer-web-component-library.js

Part of https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1049

Add OMBInfo ESLint migration rule

---

packages/documentation/src/components/dashboard/DashboardDataFetch.jsx

Enables single app build check for prod column in the support dashboard.
Tested locally.

Check single app builds for prod

---

packages/documentation/src/components/dashboard/CommitsTable.jsx
packages/documentation/src/components/dashboard/DashboardDataFetch.jsx

Currently, the FE support dashboard shows that all successful single app build commits were deployed to prod. This may not be the case if the app is opted out of continuous deployment. This PR updates the dashboard to account for continuous deployment being disabled for apps in single app build commits in the prod column. Additionally, an icon will be displayed whenever a commit has continuous deployment enabled.
Tested locally.
The last two commits in the screenshots are for single app builds that are opted out of continuous deployment.
**Current dashboard**
**Updated dashboard**
**Commits with continuous deployment icon**

Account for CD being disabled in support dashboard

---

packages/eslint-plugin/index.js
packages/eslint-plugin/lib/rules/migrate-radio-buttons.js

With the deprecation of the React RadioButtons component in favor of [va-button web component](https://design.va.gov/storybook/?path=/docs/components-va-radio--default), we are changing the ESLint warning to an error.
Related ESLint rule references in vets-website: https://github.com/department-of-veterans-affairs/vets-website/pull/22331
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1114
VS Code

Add eslint rule for RadioButtons deprecation

---

packages/eslint-plugin/index.js
packages/eslint-plugin/lib/config/recommended.js
packages/eslint-plugin/lib/rules/telephone-contact-digits.js
packages/eslint-plugin/package.json
packages/eslint-plugin/tests/lib/rules/telephone-contact-3-or-10-digits.js
packages/eslint-plugin/tests/lib/rules/telephone-contact-digits.js

We have added the [SMS prop](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1246) to va-telephone and this update adds 5 and 6 digit linting for that component so that the rule now allows 3, 5, 6, and 10 digits. Because we expanded this beyond the original 3 and 10 digits, the file was renamed to something more general as well (from `telephone-contact-3-or-10-digits` to `telephone-contact-digits`).
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1257
vets-website locally

Update telephone-contact eslint rule for SMS variation

---

packages/formation/package.json
packages/formation/sass/modules/_m-form-elements.scss

As part of the work needed for [fixing va-radio button alignment](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1345), we also want to update the Formation radio option padding so that it is consistent when used in the Forms Library.
This update will make the Forms Library RadioWidget option spacing consistent with the va-radio web component. 
Locally with vets-website
**Forms Library RadioWidget**
**Web Component (as updated [in this PR](https://github.com/department-of-veterans-affairs/component-library/pull/584))**
---
The react component uses [an additional css class `.errorable-radio-button`](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/modules/_m-form-elements.scss#L23-L …

Update Formation radio option spacing 

---

.github/CODEOWNERS
packages/documentation/src/pages/getting-started/workflow/deploy.mdx
packages/documentation/src/pages/platform/front-end-standards/manual-reviews.mdx
packages/documentation/src/pages/platform/front-end-standards/security.mdx

update references to platform-release-tools to va-platform-cop-frontend to account for reorg team changes

update references to platform-release-tools to va-platform-cop-frontend

---

packages/eslint-plugin/index.js
packages/eslint-plugin/lib/config/recommended.js
packages/eslint-plugin/lib/rules/use-new-utility-classes.js
packages/eslint-plugin/package.json
packages/eslint-plugin/tests/lib/rules/use-new-utility-classes.js

Part of https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1343
This adds two new custom ESLint rules:
This Eslint rule will help VFS teams to easily update to the new CSS Class library based on USWDS v3. 
This is a recommendable ESLint rule which will trigger on the pattern `vads-u`. 
- Testing in `vets-website`
Local testing in `vets-website` using:

Add ESLint rule for new CSS Classes

---

packages/eslint-plugin/index.js
packages/eslint-plugin/lib/config/recommended.js
packages/eslint-plugin/lib/rules/remove-expanding-group.js
packages/eslint-plugin/package.json

This will add a warning for the `ExpandingGroup` React component's deprecation.
The warning message will read:
> The ExpandingGroup React component is deprecated. Please replace with a custom solution. Also note that the wizard pattern is deprecated as well. See "Retrofit this pattern" for additional guidance if needed: https://design.va.gov/patterns/wizards#retrofit-this-pattern
Related issue: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1378
VS Code
vets-website locally

Add ESLint rule for the ExpandingGroup React component

---

CONTRIBUTING.md
README.md

[Chelen had asked that this link be fixed 3 years ago](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/199#issuecomment-660284430), and lo that day is today!
This PR is dependent on https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/1562. I tested locally that the page loads and that a redirect from the previous location works.

Fix readme 199

---

packages/formation/package.json
packages/formation/sass/modules/_m-action-link.scss

Long text in an action link would wrap underneath an icon, particularly the case on mobile view where a screen width is narrow. 
Related to the following issue https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1590
Only tested within vets-website. Not familiar with any other testing methods here. If someone from design team could please test on your end.
Before
After

updating action-links styling for proper long text wrap

---

packages/documentation/src/pages/frontend-support-dashboard/lighthouse-performance-report/lighthouse-report.json

Add entry for MHV Landing page to FE Performance Report dashboard.
Currently, [the report exists in s3](https://vetsgov-website-builds-s3-upload-test.s3-us-gov-west-1.amazonaws.com/lighthouse/my-health.html), although it is showing a warning due to a client-side redirect related to feature flags currently in place.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/56326

Add my-health entry for FE performance dashboard

---

packages/documentation/src/pages/platform/tools/feature-toggles.mdx

Documentation update, of flipper dash URLs, per  https://dsva.slack.com/archives/CBU0KDSB1/p1680787778994799

updating documentation for enabling and disabling flipper features URL

---

packages/formation/package.json
packages/formation/sass/modules/_m-action-link.scss

Fix issue where there was an underline under the icon on the action link in Safari.
- Made the link position:relative
- Made the :before icon position absolute
- Adjusted spacing to match
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1706
Browser testing in chrome and safari

Bug fix for action link icon having an underline in Safari

---

packages/formation/package.json
packages/formation/sass/modules/_m-action-link.scss

During testing of the latest changes to remove the underline from the icon, I discovered that there were alignment issues with the text and icon. This change is to fix that.
Chrome, Safari
Before: 
After:

1706 - action link alignment issues

---

packages/formation/package.json
packages/formation/sass/modules/_m-button.scss

close https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1798
A few tickets have come in with buttons that overflow from the container they are in when viewing a form in a mobile resolution. This has been fixable in many of these tickets by adding `box-sizing: border-box` to the buttons so their width can be calculated correctly. This PR addresses this by adding `box-sizing: border-box` to all buttons.
Manual testing
Before:
After:

1798 - Overflowing button

---

packages/eslint-plugin/lib/rules/prefer-web-component-library.js
packages/eslint-plugin/package.json
packages/eslint-plugin/tests/lib/rules/prefer-web-component-library.js

The design system team has deprecated the Table React component. Now that the component has been completely removed from vets-website, this will remove the eslint transformer which is no longer needed.
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1658
N/A

Remove Table eslint transformer

---

packages/eslint-plugin/lib/config/recommended.js

In two different repos as I have found uses `babel-eslint`.
- `vets-website`
- `veterans-facing-services-tools`
Please see the package at https://www.npmjs.com/package/babel-eslint which suggests using `@babel/eslint-parser`.
Why do we need this updated?
- The package `babel-eslint` has been deprecated and has not been active for 3 years now. It has been deprecated in favor of `@babel/eslint-parser`.
- The package also has not been receiving maintenance and also no updates either.
- This will also help anyone in the future that wants to create a new repo and would like to utilize the `@department-of-veterans-affairs/recommended` eslint plugin.
- For our Identity team,  we are creating our own Sign-in-Service dashboard, it would be great to be able to take small steps to update and replace …

[Chore] Replace `babel-eslint` with `@babel/eslint-parser`

---

packages/eslint-plugin/lib/rules/prefer-web-component-library.js
packages/eslint-plugin/package.json
packages/eslint-plugin/tests/lib/rules/prefer-web-component-library.js

This PR removes an eslint transformer for the OMBInfo React component which has been removed from the component-library repo
local testing
n/a

remove eslint transformer for OMBInfo

---

packages/formation/package.json
packages/formation/sass/_shame.scss
packages/formation/sass/base/_b-variables.scss
packages/formation/sass/utilities/_background-color.scss
packages/formation/sass/utilities/_border.scss
packages/formation/sass/utilities/_color.scss

Relates to [#2047](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2047).
Changes the name of color-warning-message to color-feedback-warning-background.
Tested locally; builds OK, and passes tests.
No visual changes.

Replacing color-warning-message color name

---

packages/eslint-plugin/index.js
packages/eslint-plugin/lib/config/recommended.js
packages/eslint-plugin/lib/rules/prefer-button-component.js
packages/eslint-plugin/lib/rules/prefer-table-component.js
packages/eslint-plugin/package.json
packages/eslint-plugin/tests/lib/rules/prefer-button-component.js
packages/eslint-plugin/tests/lib/rules/prefer-table-component.js

Closes [2046 add eslint for va-button and va-table](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2046)
Display eslint rule when html tag `button` or `input` with type `button` is used instead of `va-button`.
Note: tried to add a fixer as well, but found that it would break if the button text was a variable or JSX because they would already be evaluated so it wouldn't be possible to move them to the `va-button`'s `text` prop.
Display eslint rule when html tag `table` is used instead of `va-button`.
Due to similar complexities, no fixer was written for this rule.
Local unit tests
Tested in `vets-website` repo locally

Add button eslint rule for va-button and va-table

---

packages/formation/package.json
packages/formation/sass/base/_b-variables.scss

Update the current blue colors in formation to use the USWDS v3 colors. Color mappings are as follows:
```
//================
//  USWDS Colors
//===============
$color-aqua:                 #00bde3;
$color-aqua-dark:            #009ec1;
$color-aqua-lightest:        #e1f3f8;
$color-blue:                 #005ea2;
$color-blue-darkest:         #162e51;
$color-primary:              $color-blue;
$color-primary-darker:       #1a4480;
$color-primary-darkest:      $color-blue-darkest;
$color-primary-alt:          $color-aqua;
$color-primary-alt-light:    #97d4ea;
$color-primary-alt-lightest: $color-aqua-lightest;
$color-primary-alt-dark:     #28a0cb;
```
Issue link: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2228
- Local testing on vets-website. I am …

formation: update blue colors to USWDS v3 colors

---

packages/eslint-plugin/lib/rules/prefer-web-component-library.js
packages/eslint-plugin/package.json
packages/eslint-plugin/tests/lib/rules/prefer-web-component-library.js

This PR removes the `breadcrumb` eslint transformer as its no longer needed because it has been replaced with the web component.
closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1632

remove breadcrumb eslint transformer

---

packages/formation/sass/modules/_m-action-link.scss

Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2208
The icon for action link uses a pseudo-selector. The way to hide this from screen readers is to provide blank alt text to that property.
Unfortunately, not all browsers support it (Firefox, Safari), so a fallback is needed to show the icon. In these browsers, JAWS would still land on the icon. This may be the best we can do at the moment because this icon comes from the CSS.
- I tested with and without this setting in JAWS. Video attached. You will see that when this is added, it skips over the icon. When it is removed, it stops on the icon.
https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/assets/100248909/17f352c8-52b8-496d-8dd0-469eb2903c35
- I also tested …

Set alt text for action link icon to hide from JAWS

---

packages/formation/package.json

We had previously thought that we could release v8.0.0 but this version was [already published](https://www.npmjs.com/package/@department-of-veterans-affairs/formation/v/7.0.3?activeTab=versions) 2 years ago. We want to make a major release though because the [auditing of shame.scss](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/992) is a potentially breaking change.
After some discussion, we decided to skip v8.0.0 entirely and go directly to v9.0.0.

Update Formation to v9.0.0 for publishing

---

packages/formation/package.json

This updates the Font Awesome version to the latest available release. 
related https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2280
Tested using Verdacio locally. I confirmed that before this update, the icon `fa-phone-alt` did not display in vets-website and after making this update, it displayed.
Tested in vets-website locally

Update Font Awesome to v5.15.4

---

packages/formation/package.json
packages/formation/sass/base/_va.scss

I did an audit of the styles in [formation/sass/base/_va.scss](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/base/_va.scss) and this PR is doing a few things:
1. Remove any classes that I could not find being used in vets-website or content-build
2. Remove the styles that were only being used on the PageNotFound page in the dhp-connected-devices app and moved them to the app: https://github.com/department-of-veterans-affairs/vets-website/pull/27086
3. Labeled the styles that are being moved to the CSS Library: https://github.com/department-of-veterans-affairs/component-library/pull/981
**related issue** 
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2043
tested locally with …

Removing unused styles from `base/_va.scss`

---

packages/formation/package.json
packages/formation/sass/base/_b-breakpoints.scss
packages/formation/sass/base/_b-variables.scss
packages/formation/sass/base/_va.scss
packages/formation/sass/modules/_m-print.scss

We moved some styles over to the CSS Library in the following PRs and this will just add a comment in Formation to help us identify them:
- https://github.com/department-of-veterans-affairs/component-library/pull/981
- https://github.com/department-of-veterans-affairs/component-library/pull/982
N/A

Add a comment to styles that have been added to the CSS Library

---

packages/formation/package.json
packages/formation/sass/base/_va.scss
packages/formation/sass/modules/_m-nav-sidebar.scss
packages/formation/sass/site/_m-vet-nav.scss

We have removed `.va-button-primary` usages in vets-website and content-build so this PR adds a comment above the class identifying it as deprecated.
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2312
- https://github.com/department-of-veterans-affairs/vets-website/pull/27307
- https://github.com/department-of-veterans-affairs/content-build/pull/1860
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/2386
N/A
N/A

Add comment to deprecated .va-button-primary class

---

packages/formation/package.json
packages/formation/sass/base/_va.scss

Update the style to set the font color instead of the background color. The background color was causing the text to disappear in the link active state. The variable was being used to set the wrong property.
Ticket: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2321
Local testing using chrome inspector
Before: 
After:

Change background property to color on a:active

---

.github/workflows/continuous-integration.yml
packages/formation/package.json
packages/formation/sass/base/_va.scss

We have removed .card usages in vets-website and content-build so this PR adds a comment above the class identifying it as deprecated.
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2337
- https://github.com/department-of-veterans-affairs/content-build/pull/1888
- https://github.com/department-of-veterans-affairs/vets-website/pull/27541
N/A
N/A

Add comment to deprecated .card class

---

packages/formation/sass/base/_b-breakpoints.scss

We have added the breakpoints to the CSS Library and this just adds a notation in the corresponding Formation file.
- https://github.com/department-of-veterans-affairs/component-library/pull/1042

Add CSS Library notation to breakpoints

---

packages/formation/package.json
packages/formation/sass/formation-overrides/_variables.scss
packages/formation/sass/mobile-typography.scss

This PR updates the `$h1-font-size `variable definition in formation from using the `!important` flag to the `!default` flag.
Manual testing

Refactor: Change $h1-font-size from !important to !default

---

packages/eslint-plugin/package.json

Bump eslint-plugin version to 1.16.0 to release the updated React Modal eslint rule

Bump eslint-plugin version to 1.16.0

---

packages/eslint-plugin/lib/config/recommended.js
packages/eslint-plugin/package.json

Follow up to [PR #1028](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/1028). Only commenting a rule out in index.js is causing an error when trying to commit to `vets-website`:
`error    Definition for rule '@department-of-veterans-affairs/use-workspace-imports' was not found  @department-of-veterans-affairs/use-workspace-imports`
It appears the reference in `recommended.js` is causing this error which prevents git commits. Commenting it out here fixes the issue when tested locally.
Tested committing to `vets-website` before and after the change

Comment out use-workspace-imports to unblock vets-website commits

---

packages/eslint-plugin/lib/rules/prefer-icon-component.js
packages/eslint-plugin/package.json
packages/eslint-plugin/tests/lib/rules/prefer-icon-component.js

We have a Font Awesome to USWDS [name mapping table](https://design.va.gov/foundation/icons) available now so this PR will update the Storybook link to the mapping tables

Update va-icon name prop migration guidance with icon name mapping link

---

packages/eslint-plugin/index.js
packages/eslint-plugin/lib/config/recommended.js
packages/eslint-plugin/lib/rules/prefer-icon-component-message.js
packages/eslint-plugin/package.json
packages/eslint-plugin/tests/lib/rules/prefer-icon-component-message.js

We're adding a separate eslint rule for va-icon that will just display a message instead of a [migration script.](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/1025) We realized that the migration was happening during `git commit` unexpectedly and it was causing confusion. 
For now, this message only eslint rule can be used until we're ready to replace it with the migration script.
This PR also removes the original migration rule `prefer-icon-component` from being loaded completely so it should not be connected whatsoever in vets-website until added back here again.
Locally
related issue: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2534

Add va-icon eslint rule with message only

---

packages/formation/package.json
packages/formation/sass/base/_b-variables.scss
packages/formation/sass/modules/_m-button.scss
packages/formation/sass/modules/_m-dropdown.scss

Hard code in px the height and width of the size of the "search" icon in the header to make the injected header on teamsites look the same as the header on va.gov.
local testing
**search icon in header before**:
**search icon in header after**:

hard code height and width of search icon svg in px for teamsites

---

packages/formation/package.json
packages/formation/sass/base/_b-functions.scss

Modifies the `units()` helper to use scale-rem before returning the value. 
- local testing with verdaccio shows that the update here scales rem correctly down to 0.75rem, and that computed font-size value is identical to staging:
<details><summary>Local /health-care/refill-track-prescriptions/ page</summary>
</details>
<details><summary>Staging /health-care/refill-track-prescriptions/ page </summary>
</details>

modify units function to use scale rem helper

---

packages/formation/package.json
packages/formation/sass/base/_va.scss
packages/formation/sass/formation-overrides/components/_banner.scss
packages/formation/sass/formation-overrides/components/_forms.scss
packages/formation/sass/formation-overrides/elements/_inputs.scss
packages/formation/sass/modules/_m-form-elements.scss
packages/formation/sass/modules/_m-megamenu.scss
packages/formation/sass/site/_m-vet-nav.scss

This PR adds fixes to make the injected teamsites header render correctly.
related https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2730
Local testing with verdaccio / vets-website.
<hr/>
<hr /> 
<hr />
**before**
**after**

updates to make injected header render correctly

---

packages/formation/package.json
packages/formation/sass/core.scss
packages/formation/sass/formation-overrides/foundation-sites.scss

The foundation-sites npm module is used in a couple places on vets-website to apply grid/row/column layout and styles. This npm module uses rem values that need to be overwritten. This PR adds a file to formation to overwrite those rem values.
Local testing with verdaccio
```
.row {
max-width: 62.5rem
}
.row .row {
margin: 0 -.9375rem;
}
.column,
.columns {
padding-left: .9375rem;
padding-right: .9375rem;
}
@media only screen {
.column,
.columns {
padding-left: .9375rem;
padding-right: .9375rem;
}
.row.small-uncollapse>.column,
.row.small-uncollapse>.columns {
padding-left: .9375rem;
padding-right: .9375rem;
}
}
@media only screen and (min-width:40.0625em) {
.column,
.columns {
padding-left: .9375rem;
padding-right: .9375rem;
}
.row.medium-uncollapse>.column, …
```

add foundation-sites grid overrides file for rem adjustment

---

packages/formation/package.json
packages/formation/sass/base/_va.scss
packages/formation/sass/formation-overrides/components/_banner.scss
packages/formation/sass/formation-overrides/elements/_typography.scss
packages/formation/sass/modules/_m-action-link.scss
packages/formation/sass/modules/_m-breadcrumbs.scss
packages/formation/sass/modules/_m-button.scss

Updates needed from [QA'ing the USWDS normalization import for Source Sans Pro](https://github.com/department-of-veterans-affairs/vets-website/pull/30089).
related issue https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2854
Verdaccio + vets-website

Formation: Font normalization adjustments

---

packages/formation/package.json
packages/formation/sass/formation-overrides/elements/_typography.scss
packages/formation/sass/modules/_m-megamenu.scss

We got [feedback from QA review](https://dsva.slack.com/archives/C06V7AAFVH7/p1718743093470589?thread_ts=1718742362.995919&cid=C06V7AAFVH7) that the megamenu marketing card paragraph font size was too small. 
This also adds header style to linked headers.
related pr https://github.com/department-of-veterans-affairs/vets-website/pull/30089
related issue https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2909
locally
**before**
**after**

Formation: update megamenu marketing text card font-size

---

packages/formation/package.json
packages/formation/sass/formation-overrides/elements/_typography.scss

Sometimes a header is linked so it includes the `a` element. With the font normalization styles being applied from the CSS Library, this was causing a regression with the header styles which have distinct sizing and font-family. This update will make sure that anchor links used inside of header tags will have the "Bitter" serif font.
**before**
**after**

Formation: add font-family to linked header styles

---

packages/eslint-plugin/index.js
packages/eslint-plugin/lib/config/recommended.js
packages/eslint-plugin/package.json

- Add prefer-icon-component rule to eslint-plugin/index.js file
- Bump package.json version for eslint-plugin/package.json

2931 Add prefer-icon-component rule to eslint-plugin/index.js file

---

packages/formation/package.json
packages/formation/sass/modules/_m-megamenu.scss

We got [feedback from QA review](https://dsva.slack.com/archives/C06V7AAFVH7/p1718743093470589?thread_ts=1718742362.995919&cid=C06V7AAFVH7) that the megamenu marketing card header (which is just an anchor tag) font size was too large. Content was overflowing because of it.
related pr https://github.com/department-of-veterans-affairs/vets-website/pull/30089
related issue https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2909
local
**before**
**after**

Formation: update megamenu marketing box link font size

---

packages/formation/package.json
packages/formation/sass/site/_m-vet-nav.scss

The sign-in button needs a line-height added because the normalization default line-height of 1.5 was creating too much spacing compared to prod. The value added is the line-height value calculated from prod.
**before**
**after**

Formation: add sign-in button line-height

---

packages/formation/package.json
packages/formation/sass/base/_va.scss

Original issue - https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2981
Local testing with verdaccio to confirm the fix works

add a tag to va-introtext styles

---

packages/formation/package.json
packages/formation/sass/core.scss

Removes imports for `utilities/color` and `utilities/background-color` as per [#3060](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3060)
Locally with yarn test
Locally with Verdaccio

CSS Library - Utilities - Swap background-color and color imports 

---

packages/formation/README.md
packages/formation/sass/core.scss

Removes imports for `utilities/color` and `utilities/background-color` as per [#3060](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3060)
Locally with yarn test
Locally with Verdaccio

CSS Library - Utilities - comment out  background-color and color imports

---

packages/formation/package.json
packages/formation/sass/core.scss

This will comment out the Formation measure utilities import so that we can switch it over to CSS Library.
related https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3214
Verdaccio + vets-website
- Formation utilities loading and taking precedence over CSS Library:
- Formation utilities module no longer loading and the CSS Library utility is active:

Comment out measure utility for css-library changeover

---

packages/formation/package.json
packages/formation/sass/core.scss

Comment out the line-height imports. These styles will now be consumed by vets-website via the css-library
issue: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3212
verdacio testing to make sure that line-height styles are still present in vets-website
No visual changes
- [ x] Changes have been tested in vets-website
- [ x] Changes have been tested in IE11, if applicable
- [ x] Documentation has been updated, if applicable
- [x ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

Formation/core: comment out line-height import

---

packages/formation/package.json
packages/formation/sass/base/_b-mixins.scss

Updates grid mixin to use `!important` as we migrate to css-library

update grid mixins

---

packages/formation/package.json
packages/formation/sass/base/_b-mixins.scss
packages/formation/sass/core.scss

This will comment out the visibility utilities import so that the CSS Library utilities stylesheet will be used instead.
I'm also reverting the important keyword on the grid utilities because we will need to do a little more testing. [related CSS Library PR](https://github.com/department-of-veterans-affairs/component-library/pull/1318).
related issue https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3218
Locally with Verdaccio

Remove visibility utility import for CSS Library swap and revert important on grid classes

---

packages/formation/sass/_shame.scss
packages/formation/sass/modules/_m-omb-info.scss

This PR removes any horizontal padding for `.progress-box` and `.omb-info--container` to better left-align content on the introduction page and within forms. For narrower (mobile) screens, this padding 
- https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/1548 (ticket)
- https://github.com/department-of-veterans-affairs/vets-website/pull/31870 (vets-website)
- https://github.com/department-of-veterans-affairs/component-library/pull/1324 (component library)
- https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/1056 (formation)
Manual/visual testing
|         | Before | After |
| ------- | ------ | ----- |
| Desktop | <img width="750" alt="progress-box highlighted in the dev panel showing left & right padding" …

Global | Remove progress-box padding

---

packages/formation/package.json
packages/formation/sass/core.scss

Commenting out the position utilities for changing over to the CSS Library utilities stylesheet.
related issue https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3216
locally with verdaccio

Comment out position utilities import for CSS Library import swap

---

packages/formation/package.json
packages/formation/sass/core.scss

Removing the [height-width utilities](https://design.va.gov/foundation/utilities/height-and-width) import for switching over to the CSS Library.
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3210
- https://github.com/department-of-veterans-affairs/vets-website/pull/31947

Remove height-width utilities import for css-library changeover

---

packages/formation/package.json
packages/formation/sass/core.scss

Comment out font-style, font-family, font-weight, and text-decoration imports. `css-library` will supply these styles to vets-website
issue: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3198
local testing with verdaccio
no visual changes

comment out font related utils

---

packages/formation/package.json
packages/formation/sass/core.scss

Comment out the `-display` imports to make way for these utilities to be supplied by `css-library`.
issue: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3201
local testing with verdaccio

bump to 11.0.23

---

packages/formation/package.json
packages/formation/sass/core.scss

Removing the [padding utilities](https://design.va.gov/foundation/utilities/padding) import for switching over to the CSS Library.
Partial: [CSS Library - Utilities - Swap padding import #3215](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3215)
Related ticket: [Swap padding classes from formation to CSS Library #32089
](https://github.com/department-of-veterans-affairs/vets-website/pull/32089)

Remove padding import from core.scss

---

packages/formation/package.json
packages/formation/sass/core.scss

[Last PR](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/1061) forgot to bump version number. Just fixing that.

bump version number

---

packages/formation/package.json
packages/formation/sass/core.scss

This PR will comment out the [font-size](https://design.va.gov/foundation/utilities/font-size) and [flex](https://design.va.gov/foundation/utilities/flexbox) utility imports for the CSS Library changeover.
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3209
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3208

Remove font-size and flex utilities import for CSS Library changeover

---

packages/formation/package.json
packages/formation/sass/core.scss

The padding migration isn't quite done yet so I'm reverting the change that removes the import so that it isn't a blocker from going forward with other utility migrations.

Revert padding utilities import removal

---

packages/formation/package.json
packages/formation/sass/core.scss

Removes FA imports from Formation in order to completely  from vets website and content build.
Addresses part of: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2944
Tested on local builds with vets-website and content-build

Removes FA imports from Formation

---

packages/formation/README.md

This PR will add a deprecation notice to the Formation readme. The [NPM package page](https://www.npmjs.com/package/@department-of-veterans-affairs/formation) has already been updated.

Add Formation deprecation message to readme

---

.github/workflows/codeql.yml
.github/workflows/install/action.yml
packages/eslint-plugin/lib/rules/prefer-button-component.js
packages/eslint-plugin/package.json
packages/eslint-plugin/tests/lib/rules/prefer-button-component.js
packages/eslint-plugin/yarn.lock

This updates the `prefer-button-component` ESLint rule with an autofix script that will convert `button`, `input type=button`, and `usa-button` markup to the `va-button` web component.
The intention of this migration script isn't to perform a perfect migration for every scenario but it will hopefully make it easier and faster to migrate.
related https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3736
- Local unit testing 
- Testing in vets-website
Local testing linking the ESLint Plugin with vets-website locally:
1. In this `eslint-plugin` directory run `yarn link`
2. In the `vets-website` directory, run `yarn link @department-of-veterans-affairs/eslint-plugin`
3. Restart the editors ESLint server.
- In VS Code, type Shift+CMD+P and select “ESLint: …

And auto fix to the button/va-button rule
